/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/assets/environment.glb --shadows --instance --transform --output=public/assets/environment.jsx --console --root=./public 
Files: public/assets/environment.glb [11.58MB] > /home/luca/venezia-website/public/assets/environment-transformed.glb [680.07KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/environment-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Venice_Water_01.geometry} material={materials.Def_Water} position={[7.229, 0, -0.786]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge.geometry} material={materials.Def_Building} position={[0.038, -0.007, -0.001]} scale={0.01} />
      <instancedMesh args={[nodes.Mesh029.geometry, materials.Def_Building, 23]} castShadow receiveShadow instanceMatrix={nodes.Mesh029.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh015.geometry, materials.Def_Building, 18]} castShadow receiveShadow instanceMatrix={nodes.Mesh015.instanceMatrix} />
      <instancedMesh args={[nodes.Balcony_Column.geometry, materials.Def_Building, 14]} castShadow receiveShadow instanceMatrix={nodes.Balcony_Column.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/assets/environment-transformed.glb')

