/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/venice-transformed.glb --root=./public --output=public/assets/model.jsx --shadows --console 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/venice-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.MS_Disney_Wish_19.geometry} material={nodes.MS_Disney_Wish_19.material} position={[-26.036, -0.765, 53.919]} rotation={[Math.PI, 0, Math.PI]} scale={0.531} />
      <instancedMesh args={[nodes.Pole.geometry, nodes.Pole.material, 36]} castShadow receiveShadow instanceMatrix={nodes.Pole.instanceMatrix} />
      <instancedMesh args={[nodes.PowerLineReceiver.geometry, nodes.PowerLineReceiver.material, 18]} castShadow receiveShadow instanceMatrix={nodes.PowerLineReceiver.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh035.geometry, nodes.Mesh035.material, 19]} castShadow receiveShadow instanceMatrix={nodes.Mesh035.instanceMatrix} />
      <instancedMesh args={[nodes.Mesh004.geometry, nodes.Mesh004.material, 310]} castShadow receiveShadow instanceMatrix={nodes.Mesh004.instanceMatrix} />
      <instancedMesh args={[nodes.Window3.geometry, nodes.Window3.material, 5]} castShadow receiveShadow instanceMatrix={nodes.Window3.instanceMatrix} />
      <instancedMesh args={[nodes.SlantedSlab.geometry, nodes.SlantedSlab.material, 9]} castShadow receiveShadow instanceMatrix={nodes.SlantedSlab.instanceMatrix} />
      <instancedMesh args={[nodes.WoodenPlank1.geometry, nodes.WoodenPlank1.material, 20]} castShadow receiveShadow instanceMatrix={nodes.WoodenPlank1.instanceMatrix} />
      <instancedMesh args={[nodes.WoodenRod.geometry, nodes.WoodenRod.material, 19]} castShadow receiveShadow instanceMatrix={nodes.WoodenRod.instanceMatrix} />
      <instancedMesh args={[nodes.Cube031.geometry, nodes.Cube031.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Cube031.instanceMatrix} />
      <instancedMesh args={[nodes.Rock.geometry, nodes.Rock.material, 44]} castShadow receiveShadow instanceMatrix={nodes.Rock.instanceMatrix} />
      <instancedMesh args={[nodes.LampMount.geometry, nodes.LampMount.material, 5]} castShadow receiveShadow instanceMatrix={nodes.LampMount.instanceMatrix} />
      <instancedMesh args={[nodes.LampShade.geometry, nodes.LampShade.material, 5]} castShadow receiveShadow instanceMatrix={nodes.LampShade.instanceMatrix} />
      <instancedMesh args={[nodes.LampDecoratedRod.geometry, nodes.LampDecoratedRod.material, 5]} castShadow receiveShadow instanceMatrix={nodes.LampDecoratedRod.instanceMatrix} />
      <instancedMesh args={[nodes.Frame4.geometry, nodes.Frame4.material, 597]} castShadow receiveShadow instanceMatrix={nodes.Frame4.instanceMatrix} />
      <instancedMesh args={[nodes.Hinge.geometry, nodes.Hinge.material, 7356]} castShadow receiveShadow instanceMatrix={nodes.Hinge.instanceMatrix} />
      <instancedMesh args={[nodes.Shutter4.geometry, nodes.Shutter4.material, 1194]} castShadow receiveShadow instanceMatrix={nodes.Shutter4.instanceMatrix} />
      <instancedMesh args={[nodes.Frame6.geometry, nodes.Frame6.material, 215]} castShadow receiveShadow instanceMatrix={nodes.Frame6.instanceMatrix} />
      <instancedMesh args={[nodes.Building_4002.geometry, nodes.Building_4002.material, 430]} castShadow receiveShadow instanceMatrix={nodes.Building_4002.instanceMatrix} />
      <instancedMesh args={[nodes.BalconyColumn.geometry, nodes.BalconyColumn.material, 12]} castShadow receiveShadow instanceMatrix={nodes.BalconyColumn.instanceMatrix} />
      <instancedMesh args={[nodes.BaseSpeaker.geometry, nodes.BaseSpeaker.material, 12]} castShadow receiveShadow instanceMatrix={nodes.BaseSpeaker.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/assets/venice-transformed.glb')

