/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/venice.glb --root=./public --output=public/assets/model.tsx --shadows --transform --keepmeshes --typed 
Files: public/assets/venice.glb [8.91MB] > D:\projects\venezia-website\public\assets\venice-transformed.glb [836.3KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

export type GLTFResult = GLTF & {
  nodes: {
    Navmesh: THREE.Mesh
    Water: THREE.Mesh
    MS_Disney_Wish_19: THREE.Mesh
    Bridge: THREE.Mesh
    Pole001: THREE.Mesh
    Pole002: THREE.Mesh
    Pole003: THREE.Mesh
    Pole004: THREE.Mesh
    Pole005: THREE.Mesh
    Pole006: THREE.Mesh
    Pole007: THREE.Mesh
    Pole008: THREE.Mesh
    Pole009: THREE.Mesh
    Pole010: THREE.Mesh
    Pole011: THREE.Mesh
    Pole012: THREE.Mesh
    Pole013: THREE.Mesh
    Pole014: THREE.Mesh
    Pole015: THREE.Mesh
    Pole016: THREE.Mesh
    Pole017: THREE.Mesh
    Pole018: THREE.Mesh
    Pole019: THREE.Mesh
    Pole020: THREE.Mesh
    Pole021: THREE.Mesh
    Pole022: THREE.Mesh
    Pole023: THREE.Mesh
    Pole024: THREE.Mesh
    Pole025: THREE.Mesh
    Pole028: THREE.Mesh
    Building_1: THREE.Mesh
    Power_Line_Receiver013: THREE.Mesh
    Power_Line_Receiver014: THREE.Mesh
    Power_Line_Receiver015: THREE.Mesh
    Power_Line_Receiver016: THREE.Mesh
    Power_Line_Receiver017: THREE.Mesh
    Power_Line_Receiver018: THREE.Mesh
    Power_Line_Receiver007: THREE.Mesh
    Power_Line_Receiver008: THREE.Mesh
    Power_Line_Receiver009: THREE.Mesh
    Power_Line_Receiver010: THREE.Mesh
    Power_Line_Receiver011: THREE.Mesh
    Power_Line_Receiver012: THREE.Mesh
    Power_Line_Receiver001: THREE.Mesh
    Power_Line_Receiver002: THREE.Mesh
    Power_Line_Receiver003: THREE.Mesh
    Power_Line_Receiver004: THREE.Mesh
    Power_Line_Receiver005: THREE.Mesh
    Power_Line_Receiver006: THREE.Mesh
    Flower_Box001: THREE.Mesh
    Flower_Box002: THREE.Mesh
    FlowerBox001: THREE.Mesh
    FlowerBox002: THREE.Mesh
    FlowerBox003: THREE.Mesh
    FlowerBox004: THREE.Mesh
    FlowerBox005: THREE.Mesh
    FlowerBox006: THREE.Mesh
    Wall_Bracket001: THREE.Mesh
    Wall_Bracket003: THREE.Mesh
    Wall_Bracket004: THREE.Mesh
    Wall_Bracket002: THREE.Mesh
    WallBracket001: THREE.Mesh
    WallBracket003: THREE.Mesh
    Building_2: THREE.Mesh
    Window3001: THREE.Mesh
    Window3002: THREE.Mesh
    Window3004: THREE.Mesh
    Window3005: THREE.Mesh
    Window3003: THREE.Mesh
    Building_2002: THREE.Mesh
    Building_3: THREE.Mesh
    Building_3001: THREE.Mesh
    Building_3002: THREE.Mesh
    Building_3003: THREE.Mesh
    Building_4: THREE.Mesh
    Building_4001: THREE.Mesh
    Building_5: THREE.Mesh
    Building_6: THREE.Mesh
    Rooftop_AC: THREE.Mesh
    Rooftop_Access: THREE.Mesh
    Building_7: THREE.Mesh
    WestPlaza: THREE.Mesh
    CanalStairs: THREE.Mesh
    AdBoard: THREE.Mesh
    AdBoard001: THREE.Mesh
    AdBoard002: THREE.Mesh
    Bridge001: THREE.Mesh
    Bridge002: THREE.Mesh
    Bridge003: THREE.Mesh
    Bridge004: THREE.Mesh
    Bridge005: THREE.Mesh
    Bridge006: THREE.Mesh
    Bridge007: THREE.Mesh
    Bridge008: THREE.Mesh
    Bridge009: THREE.Mesh
    Bridge010: THREE.Mesh
    WoodenPlank1001: THREE.Mesh
    WoodenPlank1002: THREE.Mesh
    WoodenPlank1003: THREE.Mesh
    WoodenPlank1004: THREE.Mesh
    WoodenPlank1005: THREE.Mesh
    WoodenPlank1010: THREE.Mesh
    WoodenPlank1011: THREE.Mesh
    WoodenPlank1012: THREE.Mesh
    WoodenPlank1013: THREE.Mesh
    WoodenPlank1006: THREE.Mesh
    WoodenPlank1007: THREE.Mesh
    WoodenPlank1008: THREE.Mesh
    WoodenPlank1009: THREE.Mesh
    Building_4002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Tower: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder006: THREE.Mesh
    RoundWindow002: THREE.Mesh
    RoundWindow003: THREE.Mesh
    Cube038: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube039: THREE.Mesh
    GN_Instance: THREE.Mesh
    GN_Instance_21: THREE.InstancedMesh
    GN_Instance_24: THREE.InstancedMesh
    GN_Instance_42: THREE.InstancedMesh
    GN_Instance_73: THREE.InstancedMesh
    GN_Instance_1: THREE.InstancedMesh
    GN_Instance_22: THREE.InstancedMesh
    GN_Instance_25: THREE.InstancedMesh
    GN_Instance_43: THREE.InstancedMesh
    GN_Instance_74: THREE.InstancedMesh
    GN_Instance_2: THREE.InstancedMesh
    GN_Instance_23: THREE.InstancedMesh
    GN_Instance_26: THREE.InstancedMesh
    GN_Instance_44: THREE.InstancedMesh
    GN_Instance_75: THREE.InstancedMesh
    GN_Instance_3: THREE.InstancedMesh
    GN_Instance_4: THREE.InstancedMesh
    GN_Instance_5: THREE.InstancedMesh
    GN_Instance_6: THREE.InstancedMesh
    GN_Instance_7: THREE.InstancedMesh
    GN_Instance_8: THREE.InstancedMesh
    GN_Instance_9: THREE.InstancedMesh
    GN_Instance_10: THREE.InstancedMesh
    GN_Instance_11: THREE.InstancedMesh
    GN_Instance_12: THREE.InstancedMesh
    GN_Instance_13: THREE.InstancedMesh
    GN_Instance_14: THREE.InstancedMesh
    GN_Instance_27: THREE.InstancedMesh
    GN_Instance_28: THREE.InstancedMesh
    GN_Instance_29: THREE.InstancedMesh
    GN_Instance_30: THREE.InstancedMesh
    GN_Instance_31: THREE.InstancedMesh
    GN_Instance_32: THREE.InstancedMesh
    GN_Instance_33: THREE.InstancedMesh
    GN_Instance_34: THREE.InstancedMesh
    GN_Instance_35: THREE.InstancedMesh
    GN_Instance_36: THREE.InstancedMesh
    GN_Instance_45: THREE.InstancedMesh
    GN_Instance_46: THREE.InstancedMesh
    GN_Instance_47: THREE.InstancedMesh
    GN_Instance_48: THREE.InstancedMesh
    GN_Instance_54: THREE.InstancedMesh
    GN_Instance_55: THREE.InstancedMesh
    GN_Instance_56: THREE.InstancedMesh
    GN_Instance_57: THREE.InstancedMesh
    GN_Instance_58: THREE.InstancedMesh
    GN_Instance_59: THREE.InstancedMesh
    GN_Instance_60: THREE.InstancedMesh
    GN_Instance_61: THREE.InstancedMesh
    GN_Instance_62: THREE.InstancedMesh
    GN_Instance_63: THREE.InstancedMesh
    GN_Instance_64: THREE.InstancedMesh
    GN_Instance_65: THREE.InstancedMesh
    GN_Instance_66: THREE.InstancedMesh
    GN_Instance_67: THREE.InstancedMesh
    GN_Instance_15: THREE.InstancedMesh
    GN_Instance_16: THREE.InstancedMesh
    GN_Instance_17: THREE.InstancedMesh
    GN_Instance_18: THREE.InstancedMesh
    GN_Instance_19: THREE.InstancedMesh
    GN_Instance_20: THREE.InstancedMesh
    GN_Instance_37: THREE.InstancedMesh
    GN_Instance_38: THREE.InstancedMesh
    GN_Instance_39: THREE.InstancedMesh
    GN_Instance_40: THREE.InstancedMesh
    GN_Instance_41: THREE.InstancedMesh
    GN_Instance_49: THREE.InstancedMesh
    GN_Instance_50: THREE.InstancedMesh
    GN_Instance_51: THREE.InstancedMesh
    GN_Instance_52: THREE.InstancedMesh
    GN_Instance_53: THREE.InstancedMesh
    GN_Instance_68: THREE.InstancedMesh
    GN_Instance_69: THREE.InstancedMesh
    GN_Instance_70: THREE.InstancedMesh
    GN_Instance_71: THREE.InstancedMesh
    GN_Instance_72: THREE.InstancedMesh
    Balcony: THREE.InstancedMesh
    Balcony_1: THREE.InstancedMesh
    Balcony_Column004: THREE.InstancedMesh
    Balcony_Column004_1: THREE.InstancedMesh
    Balcony001: THREE.InstancedMesh
    Balcony002: THREE.InstancedMesh
    Window0210: THREE.InstancedMesh
    Window0220: THREE.InstancedMesh
    Window0230: THREE.InstancedMesh
    Window0240: THREE.InstancedMesh
    Window0250: THREE.InstancedMesh
    Window0260: THREE.InstancedMesh
    Window0270: THREE.InstancedMesh
    Window0280: THREE.InstancedMesh
    Window0290: THREE.InstancedMesh
    Window0300: THREE.InstancedMesh
    Window0310: THREE.InstancedMesh
    Window0320: THREE.InstancedMesh
    Window60060: THREE.InstancedMesh
    Window60070: THREE.InstancedMesh
    Window60080: THREE.InstancedMesh
    Window60090: THREE.InstancedMesh
    Window60100: THREE.InstancedMesh
    Window60110: THREE.InstancedMesh
    Window0010: THREE.InstancedMesh
    Window0020: THREE.InstancedMesh
    Window0030: THREE.InstancedMesh
    Window0040: THREE.InstancedMesh
    Window0050: THREE.InstancedMesh
    Window0060: THREE.InstancedMesh
    Window0070: THREE.InstancedMesh
    Window0080: THREE.InstancedMesh
    Window0090: THREE.InstancedMesh
    Window0100: THREE.InstancedMesh
    Window60010: THREE.InstancedMesh
    Window60020: THREE.InstancedMesh
    Window60030: THREE.InstancedMesh
    Window60040: THREE.InstancedMesh
    Window60050: THREE.InstancedMesh
    Window0330: THREE.InstancedMesh
    Window0340: THREE.InstancedMesh
    Window0350: THREE.InstancedMesh
    Window0360: THREE.InstancedMesh
    Window60170: THREE.InstancedMesh
    Window60180: THREE.InstancedMesh
    Window60190: THREE.InstancedMesh
    Window60200: THREE.InstancedMesh
    Window60210: THREE.InstancedMesh
    Window0370: THREE.InstancedMesh
    Window0380: THREE.InstancedMesh
    Window0390: THREE.InstancedMesh
    Window0400: THREE.InstancedMesh
    Window0110: THREE.InstancedMesh
    Window0120: THREE.InstancedMesh
    Window0130: THREE.InstancedMesh
    Window0140: THREE.InstancedMesh
    Window0150: THREE.InstancedMesh
    Window0160: THREE.InstancedMesh
    Window0170: THREE.InstancedMesh
    Window0180: THREE.InstancedMesh
    Window0190: THREE.InstancedMesh
    Window0200: THREE.InstancedMesh
    Window60120: THREE.InstancedMesh
    Window60130: THREE.InstancedMesh
    Window60140: THREE.InstancedMesh
    Window60150: THREE.InstancedMesh
    Window60160: THREE.InstancedMesh
    Window0211: THREE.InstancedMesh
    Window0221: THREE.InstancedMesh
    Window0231: THREE.InstancedMesh
    Window0241: THREE.InstancedMesh
    Window0251: THREE.InstancedMesh
    Window0261: THREE.InstancedMesh
    Window0271: THREE.InstancedMesh
    Window0281: THREE.InstancedMesh
    Window0291: THREE.InstancedMesh
    Window0301: THREE.InstancedMesh
    Window0311: THREE.InstancedMesh
    Window0321: THREE.InstancedMesh
    Window0011: THREE.InstancedMesh
    Window0021: THREE.InstancedMesh
    Window0031: THREE.InstancedMesh
    Window0041: THREE.InstancedMesh
    Window0051: THREE.InstancedMesh
    Window0061: THREE.InstancedMesh
    Window0071: THREE.InstancedMesh
    Window0081: THREE.InstancedMesh
    Window0091: THREE.InstancedMesh
    Window0101: THREE.InstancedMesh
    Window0331: THREE.InstancedMesh
    Window0341: THREE.InstancedMesh
    Window0351: THREE.InstancedMesh
    Window0361: THREE.InstancedMesh
    Window0371: THREE.InstancedMesh
    Window0381: THREE.InstancedMesh
    Window0391: THREE.InstancedMesh
    Window0401: THREE.InstancedMesh
    Window0111: THREE.InstancedMesh
    Window0121: THREE.InstancedMesh
    Window0131: THREE.InstancedMesh
    Window0141: THREE.InstancedMesh
    Window0151: THREE.InstancedMesh
    Window0161: THREE.InstancedMesh
    Window0171: THREE.InstancedMesh
    Window0181: THREE.InstancedMesh
    Window0191: THREE.InstancedMesh
    Window0201: THREE.InstancedMesh
    Window60061: THREE.InstancedMesh
    Window60071: THREE.InstancedMesh
    Window60081: THREE.InstancedMesh
    Window60091: THREE.InstancedMesh
    Window60101: THREE.InstancedMesh
    Window60111: THREE.InstancedMesh
    Window60011: THREE.InstancedMesh
    Window60021: THREE.InstancedMesh
    Window60031: THREE.InstancedMesh
    Window60041: THREE.InstancedMesh
    Window60051: THREE.InstancedMesh
    Window60171: THREE.InstancedMesh
    Window60181: THREE.InstancedMesh
    Window60191: THREE.InstancedMesh
    Window60201: THREE.InstancedMesh
    Window60211: THREE.InstancedMesh
    Window60121: THREE.InstancedMesh
    Window60131: THREE.InstancedMesh
    Window60141: THREE.InstancedMesh
    Window60151: THREE.InstancedMesh
    Window60161: THREE.InstancedMesh
  }
  materials: {}
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/venice-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow geometry={nodes.Water.geometry} material={nodes.Water.material} scale={46.67} />
      <mesh castShadow receiveShadow geometry={nodes.MS_Disney_Wish_19.geometry} material={nodes.MS_Disney_Wish_19.material} position={[-26.036, -0.765, 53.919]} rotation={[Math.PI, 0, Math.PI]} scale={0.531} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge.geometry} material={nodes.Bridge.material} />
      <mesh castShadow receiveShadow geometry={nodes.Pole001.geometry} material={nodes.Pole001.material} position={[-3.017, 0.729, -2.636]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole002.geometry} material={nodes.Pole002.material} position={[-3.017, 0.729, -0.958]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole003.geometry} material={nodes.Pole003.material} position={[-3.017, 0.729, -1.816]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole004.geometry} material={nodes.Pole004.material} position={[-3.017, 0.729, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole005.geometry} material={nodes.Pole005.material} position={[-3.017, 0.729, 2.077]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole006.geometry} material={nodes.Pole006.material} position={[-2.828, 0.797, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole007.geometry} material={nodes.Pole007.material} position={[-0.738, 1.319, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole008.geometry} material={nodes.Pole008.material} position={[0.723, 1.319, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole009.geometry} material={nodes.Pole009.material} position={[2.648, 0.776, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole010.geometry} material={nodes.Pole010.material} position={[2.648, 0.776, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole011.geometry} material={nodes.Pole011.material} position={[0.721, 1.317, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole012.geometry} material={nodes.Pole012.material} position={[-0.754, 1.317, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole013.geometry} material={nodes.Pole013.material} position={[-2.831, 0.78, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole014.geometry} material={nodes.Pole014.material} position={[-1.404, 1.154, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole015.geometry} material={nodes.Pole015.material} position={[1.357, 1.135, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole016.geometry} material={nodes.Pole016.material} position={[1.358, 1.136, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole017.geometry} material={nodes.Pole017.material} position={[-0.002, 1.304, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole018.geometry} material={nodes.Pole018.material} position={[-0.002, 1.304, -0.98]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole019.geometry} material={nodes.Pole019.material} position={[2.063, 0.934, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole020.geometry} material={nodes.Pole020.material} position={[2.065, 0.938, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole021.geometry} material={nodes.Pole021.material} position={[-2.137, 0.957, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole022.geometry} material={nodes.Pole022.material} position={[-2.137, 0.957, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole023.geometry} material={nodes.Pole023.material} position={[-1.401, 1.154, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole024.geometry} material={nodes.Pole024.material} position={[-3.258, 0.728, 8.902]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole025.geometry} material={nodes.Pole025.material} position={[-3.279, 0.728, 9.923]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole028.geometry} material={nodes.Pole028.material} position={[-2.93, 0.728, 9.423]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Building_1.geometry} material={nodes.Building_1.material} position={[5.535, 0.009, -3.518]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver013.geometry} material={nodes.Power_Line_Receiver013.material} position={[1.681, 6.913, -5.148]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver014.geometry} material={nodes.Power_Line_Receiver014.material} position={[1.606, 6.368, -5.15]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver015.geometry} material={nodes.Power_Line_Receiver015.material} position={[1.502, 6.368, -5.143]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver016.geometry} material={nodes.Power_Line_Receiver016.material} position={[1.746, 4.535, -1.794]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver017.geometry} material={nodes.Power_Line_Receiver017.material} position={[1.75, 4.432, -1.605]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver018.geometry} material={nodes.Power_Line_Receiver018.material} position={[1.746, 4.332, -1.801]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver007.geometry} material={nodes.Power_Line_Receiver007.material} position={[-3.629, 6.913, 1.519]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver008.geometry} material={nodes.Power_Line_Receiver008.material} position={[-3.632, 6.363, 1.453]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver009.geometry} material={nodes.Power_Line_Receiver009.material} position={[-3.632, 6.363, 1.34]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver010.geometry} material={nodes.Power_Line_Receiver010.material} position={[-6.981, 4.533, 1.591]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver011.geometry} material={nodes.Power_Line_Receiver011.material} position={[-6.98, 4.331, 1.591]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver012.geometry} material={nodes.Power_Line_Receiver012.material} position={[-7.167, 4.432, 1.593]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver001.geometry} material={nodes.Power_Line_Receiver001.material} position={[-2.412, 6.911, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver002.geometry} material={nodes.Power_Line_Receiver002.material} position={[-2.226, 6.366, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver003.geometry} material={nodes.Power_Line_Receiver003.material} position={[-2.342, 6.366, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver004.geometry} material={nodes.Power_Line_Receiver004.material} position={[-2.475, 4.534, -6.269]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver005.geometry} material={nodes.Power_Line_Receiver005.material} position={[-2.486, 4.431, -6.454]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver006.geometry} material={nodes.Power_Line_Receiver006.material} position={[-2.479, 4.331, -6.273]} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Box001.geometry} material={nodes.Flower_Box001.material} position={[1.944, 4.629, -2.487]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Box002.geometry} material={nodes.Flower_Box002.material} position={[1.944, 4.629, -4.35]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox001.geometry} material={nodes.FlowerBox001.material} position={[-4.394, 4.632, 1.791]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox002.geometry} material={nodes.FlowerBox002.material} position={[-6.299, 4.632, 1.791]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox003.geometry} material={nodes.FlowerBox003.material} position={[-10.217, 6.176, 6.422]} rotation={[1.57, 0, 3.141]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox004.geometry} material={nodes.FlowerBox004.material} position={[-11.266, 6.176, 6.422]} rotation={[1.57, 0, 3.141]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox005.geometry} material={nodes.FlowerBox005.material} position={[-11.266, 6.177, 8.898]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox006.geometry} material={nodes.FlowerBox006.material} position={[-10.216, 6.177, 8.898]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket001.geometry} material={nodes.Wall_Bracket001.material} position={[1.933, 6.469, -3.486]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket003.geometry} material={nodes.Wall_Bracket003.material} position={[-5.37, 6.492, 1.791]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket004.geometry} material={nodes.Wall_Bracket004.material} position={[-5.37, 6.492, 8.914]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket002.geometry} material={nodes.Wall_Bracket002.material} position={[-2.671, 6.483, -4.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket001.geometry} material={nodes.WallBracket001.material} position={[-10.867, 5.614, 6.405]} rotation={[-1.571, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket003.geometry} material={nodes.WallBracket003.material} position={[-10.954, 4.644, 6.405]} rotation={[-1.571, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_2.geometry} material={nodes.Building_2.material} position={[3.321, 5.83, 3.377]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3001.geometry} material={nodes.Window3001.material} position={[2.522, 8.207, 2.725]} rotation={[Math.PI / 2, 0, 1.569]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3002.geometry} material={nodes.Window3002.material} position={[2.522, 8.207, 4.729]} rotation={[Math.PI / 2, 0, 1.569]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3004.geometry} material={nodes.Window3004.material} position={[-11.326, 4.371, 8.851]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3005.geometry} material={nodes.Window3005.material} position={[-10.241, 4.371, 8.851]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3003.geometry} material={nodes.Window3003.material} position={[-12.331, 4.371, 7.667]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_2002.geometry} material={nodes.Building_2002.material} position={[2.479, 1.267, 4.748]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3.geometry} material={nodes.Building_3.material} position={[4.958, -0.015, 8.769]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3001.geometry} material={nodes.Building_3001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3002.geometry} material={nodes.Building_3002.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3003.geometry} material={nodes.Building_3003.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4.geometry} material={nodes.Building_4.material} position={[-5.471, 0.009, 5.57]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4001.geometry} material={nodes.Building_4001.material} position={[-5.471, 0.009, 5.57]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_5.geometry} material={nodes.Building_5.material} position={[-6.268, 0.001, -4.598]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_6.geometry} material={nodes.Building_6.material} position={[-1.434, 5.07, -9.805]} />
      <mesh castShadow receiveShadow geometry={nodes.Rooftop_AC.geometry} material={nodes.Rooftop_AC.material} position={[-5.682, 9.525, -9.877]} />
      <mesh castShadow receiveShadow geometry={nodes.Rooftop_Access.geometry} material={nodes.Rooftop_Access.material} position={[-4.327, 9.524, -14.467]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_7.geometry} material={nodes.Building_7.material} position={[3.953, -0.009, -11.862]} />
      <mesh castShadow receiveShadow geometry={nodes.WestPlaza.geometry} material={nodes.WestPlaza.material} position={[-13.293, -0.887, 2.8]} />
      <mesh castShadow receiveShadow geometry={nodes.CanalStairs.geometry} material={nodes.CanalStairs.material} position={[-12.674, 0.395, 9.443]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard.geometry} material={nodes.AdBoard.material} position={[-13.488, 0.788, 4.448]} rotation={[0, -1.554, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard001.geometry} material={nodes.AdBoard001.material} position={[4.924, 0.788, 16.623]} rotation={[0, -1.554, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard002.geometry} material={nodes.AdBoard002.material} position={[2.666, 0.788, 20.139]} rotation={[0, -1.554, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge001.geometry} material={nodes.Bridge001.material} position={[-8.138, 1.41, 4.178]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge002.geometry} material={nodes.Bridge002.material} position={[-9.434, 1.965, 5.271]} rotation={[0, 0.006, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge003.geometry} material={nodes.Bridge003.material} position={[-9.426, 2.116, 5.608]} rotation={[0.003, 0.032, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge004.geometry} material={nodes.Bridge004.material} position={[-9.436, 1.816, 4.924]} rotation={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge005.geometry} material={nodes.Bridge005.material} position={[-9.44, 1.665, 4.58]} rotation={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge006.geometry} material={nodes.Bridge006.material} position={[-9.434, 1.513, 4.242]} rotation={[0.003, -0.004, -0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge007.geometry} material={nodes.Bridge007.material} position={[-9.434, 1.362, 3.903]} rotation={[-0.001, 0.001, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge008.geometry} material={nodes.Bridge008.material} position={[-9.434, 1.213, 3.564]} rotation={[0.001, 0.001, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge009.geometry} material={nodes.Bridge009.material} position={[-9.434, 1.062, 3.226]} rotation={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge010.geometry} material={nodes.Bridge010.material} position={[-9.434, 0.913, 2.906]} rotation={[-0.003, -0.001, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1001.geometry} material={nodes.WoodenPlank1001.material} position={[-7.387, 1.35, 3.706]} rotation={[-0.416, 0.037, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1002.geometry} material={nodes.WoodenPlank1002.material} position={[-7.364, 1.505, 4.001]} rotation={[-0.416, 0.008, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1003.geometry} material={nodes.WoodenPlank1003.material} position={[-11.397, 6.188, 7.924]} rotation={[-0.39, -1.118, -0.357]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1004.geometry} material={nodes.WoodenPlank1004.material} position={[-12.298, 1.938, 8.266]} rotation={[-1.57, 0.059, 1.563]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1005.geometry} material={nodes.WoodenPlank1005.material} position={[-12.322, 1.933, 8.405]} rotation={[-1.57, 0.09, 1.563]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1010.geometry} material={nodes.WoodenPlank1010.material} position={[-9.229, 4.545, 7.628]} rotation={[0.361, 0, -1.571]} scale={0.77} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1011.geometry} material={nodes.WoodenPlank1011.material} position={[-9.211, 4.945, 7.826]} rotation={[2.261, -0.004, -1.574]} scale={0.77} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1012.geometry} material={nodes.WoodenPlank1012.material} position={[-10.9, 5.005, 8.955]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1013.geometry} material={nodes.WoodenPlank1013.material} position={[-10.9, 5.031, 8.955]} rotation={[0, -1.55, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1006.geometry} material={nodes.WoodenPlank1006.material} position={[-12.301, 0.786, 7.851]} rotation={[0, 0, 1.236]} scale={[1, 1, 0.889]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1007.geometry} material={nodes.WoodenPlank1007.material} position={[-12.248, 0.893, 7.967]} rotation={[0, 0, 1.483]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1008.geometry} material={nodes.WoodenPlank1008.material} position={[-12.339, 0.802, 7.967]} rotation={[0, 0, 1.483]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1009.geometry} material={nodes.WoodenPlank1009.material} position={[-12.288, 0.91, 7.946]} rotation={[0, 0, 1.214]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4002.geometry} material={nodes.Building_4002.material} position={[-10.805, 7.727, 7.075]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-9.628, 4.806, 6.397]} />
      <mesh castShadow receiveShadow geometry={nodes.Tower.geometry} material={nodes.Tower.material} position={[-10.819, 0.792, 7.653]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-16.885, -0.465, 10.945]} rotation={[-0.045, -0.028, -0.025]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-17.273, -0.495, 12.389]} rotation={[-0.076, 1.016, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-10.864, 5.855, 18.069]} rotation={[0, -0.187, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-12.602, 7.027, 17.619]} rotation={[0, -0.204, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-14.035, 5.688, 17.335]} rotation={[0, -0.204, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.RoundWindow002.geometry} material={nodes.RoundWindow002.material} position={[-10.585, 4.162, 17.53]} rotation={[Math.PI, -1.349, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.RoundWindow003.geometry} material={nodes.RoundWindow003.material} position={[-14.609, 4.145, 16.881]} rotation={[3.141, -1.373, -1.574]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[-12.617, 4.223, 17.707]} rotation={[0, -0.211, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-12.505, 4.91, 17.243]} rotation={[3.141, -1.375, -1.574]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} position={[-12.429, 2.519, 17.302]} rotation={[Math.PI, -1.36, -Math.PI / 2]} scale={1.379} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance.geometry} material={nodes.GN_Instance.material} position={[1.999, 3.751, -5.214]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_21.geometry} material={nodes.GN_Instance_21.material} position={[2.447, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_24.geometry} material={nodes.GN_Instance_24.material} position={[-3.552, 3.808, 1.796]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_42.geometry} material={nodes.GN_Instance_42.material} position={[-3.734, 4.222, 8.903]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_73.geometry} material={nodes.GN_Instance_73.material} position={[-11.615, 2.901, 8.738]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_1.geometry} material={nodes.GN_Instance_1.material} position={[0.873, 4.291, -5.214]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_22.geometry} material={nodes.GN_Instance_22.material} position={[1.197, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_25.geometry} material={nodes.GN_Instance_25.material} position={[-3.552, 4.318, 0.733]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_43.geometry} material={nodes.GN_Instance_43.material} position={[-3.734, 4.431, 10.135]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_74.geometry} material={nodes.GN_Instance_74.material} position={[-11.613, 3.71, 9.688]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_2.geometry} material={nodes.GN_Instance_2.material} position={[1.917, 3.786, -5.214]} rotation={[-Math.PI / 2, -1.12, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_23.geometry} material={nodes.GN_Instance_23.material} position={[2.357, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_26.geometry} material={nodes.GN_Instance_26.material} position={[-3.552, 3.812, 1.777]} rotation={[-2.691, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_44.geometry} material={nodes.GN_Instance_44.material} position={[-3.734, 4.235, 8.992]} rotation={[-0.17, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_75.geometry} material={nodes.GN_Instance_75.material} position={[-11.615, 2.954, 8.809]} rotation={[-0.711, 0.001, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_3.geometry} material={nodes.GN_Instance_3.material} position={[3.737, 7.497, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_4.geometry} material={nodes.GN_Instance_4.material} position={[3.737, 3.317, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_5.geometry} material={nodes.GN_Instance_5.material} position={[2.024, 3.317, -2.508]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_6.geometry} material={nodes.GN_Instance_6.material} position={[2.024, 3.317, -4.371]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_7.geometry} material={nodes.GN_Instance_7.material} position={[3.637, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_8.geometry} material={nodes.GN_Instance_8.material} position={[2.024, 7.506, -2.495]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_9.geometry} material={nodes.GN_Instance_9.material} position={[2.024, 7.506, -4.371]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_10.geometry} material={nodes.GN_Instance_10.material} position={[3.637, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_11.geometry} material={nodes.GN_Instance_11.material} position={[5.418, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_12.geometry} material={nodes.GN_Instance_12.material} position={[7.186, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_13.geometry} material={nodes.GN_Instance_13.material} position={[5.423, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_14.geometry} material={nodes.GN_Instance_14.material} position={[7.228, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_27.geometry} material={nodes.GN_Instance_27.material} position={[-3.364, 7.511, 3.481]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_28.geometry} material={nodes.GN_Instance_28.material} position={[-3.364, 7.511, 5.253]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_29.geometry} material={nodes.GN_Instance_29.material} position={[-3.364, 7.511, 7.043]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_30.geometry} material={nodes.GN_Instance_30.material} position={[-3.364, 3.312, 7.043]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_31.geometry} material={nodes.GN_Instance_31.material} position={[-3.364, 3.312, 5.253]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_32.geometry} material={nodes.GN_Instance_32.material} position={[-3.364, 3.312, 3.483]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_33.geometry} material={nodes.GN_Instance_33.material} position={[-4.405, 7.511, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_34.geometry} material={nodes.GN_Instance_34.material} position={[-6.288, 7.511, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_35.geometry} material={nodes.GN_Instance_35.material} position={[-6.279, 3.312, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_36.geometry} material={nodes.GN_Instance_36.material} position={[-4.404, 3.312, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_45.geometry} material={nodes.GN_Instance_45.material} position={[-6.283, 7.511, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_46.geometry} material={nodes.GN_Instance_46.material} position={[-4.396, 7.511, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_47.geometry} material={nodes.GN_Instance_47.material} position={[-6.283, 3.342, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_48.geometry} material={nodes.GN_Instance_48.material} position={[-4.427, 3.342, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_54.geometry} material={nodes.GN_Instance_54.material} position={[-7.34, 7.511, 3.481]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_55.geometry} material={nodes.GN_Instance_55.material} position={[-7.34, 7.511, 5.253]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_56.geometry} material={nodes.GN_Instance_56.material} position={[-7.34, 7.511, 7.043]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_57.geometry} material={nodes.GN_Instance_57.material} position={[-7.376, 3.312, 3.483]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_58.geometry} material={nodes.GN_Instance_58.material} position={[-7.928, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_59.geometry} material={nodes.GN_Instance_59.material} position={[-6.144, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_60.geometry} material={nodes.GN_Instance_60.material} position={[-4.375, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_61.geometry} material={nodes.GN_Instance_61.material} position={[-4.375, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_62.geometry} material={nodes.GN_Instance_62.material} position={[-6.139, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_63.geometry} material={nodes.GN_Instance_63.material} position={[-7.929, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_64.geometry} material={nodes.GN_Instance_64.material} position={[-2.766, 3.311, -3.698]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_65.geometry} material={nodes.GN_Instance_65.material} position={[-2.766, 3.311, -5.571]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_66.geometry} material={nodes.GN_Instance_66.material} position={[-2.766, 7.503, -5.571]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_67.geometry} material={nodes.GN_Instance_67.material} position={[-2.766, 7.503, -3.699]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_15.geometry} material={nodes.GN_Instance_15.material} position={[7.204, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_16.geometry} material={nodes.GN_Instance_16.material} position={[5.418, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_17.geometry} material={nodes.GN_Instance_17.material} position={[3.636, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_18.geometry} material={nodes.GN_Instance_18.material} position={[2.09, 5.39, -4.368]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_19.geometry} material={nodes.GN_Instance_19.material} position={[2.09, 5.39, -2.493]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_20.geometry} material={nodes.GN_Instance_20.material} position={[3.635, 5.39, -1.509]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_37.geometry} material={nodes.GN_Instance_37.material} position={[-3.424, 5.393, 7.044]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_38.geometry} material={nodes.GN_Instance_38.material} position={[-3.424, 5.393, 5.264]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_39.geometry} material={nodes.GN_Instance_39.material} position={[-3.424, 5.393, 3.476]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_40.geometry} material={nodes.GN_Instance_40.material} position={[-4.408, 5.382, 1.922]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_41.geometry} material={nodes.GN_Instance_41.material} position={[-6.279, 5.382, 1.922]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_49.geometry} material={nodes.GN_Instance_49.material} position={[-6.298, 5.393, 8.757]} rotation={[0, 0.017, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_50.geometry} material={nodes.GN_Instance_50.material} position={[-4.418, 5.393, 8.757]} rotation={[0, 0.017, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_51.geometry} material={nodes.GN_Instance_51.material} position={[-7.278, 5.393, 7.044]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_52.geometry} material={nodes.GN_Instance_52.material} position={[-7.278, 5.393, 5.264]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_53.geometry} material={nodes.GN_Instance_53.material} position={[-7.278, 5.393, 3.476]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_68.geometry} material={nodes.GN_Instance_68.material} position={[-7.858, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_69.geometry} material={nodes.GN_Instance_69.material} position={[-6.154, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_70.geometry} material={nodes.GN_Instance_70.material} position={[-4.376, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_71.geometry} material={nodes.GN_Instance_71.material} position={[-2.821, 5.393, -3.681]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_72.geometry} material={nodes.GN_Instance_72.material} position={[-2.821, 5.393, -5.561]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony.geometry} material={nodes.Balcony.material} position={[2.281, 4.184, 2.723]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_1.geometry} material={nodes.Balcony_1.material} position={[2.281, 4.184, 4.754]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_Column004.geometry} material={nodes.Balcony_Column004.material} position={[2.043, 4.272, 2.583]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_Column004_1.geometry} material={nodes.Balcony_Column004_1.material} position={[2.043, 4.272, 4.614]} />
      <instancedMesh args={[nodes.Balcony001.geometry, nodes.Balcony001.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony001.instanceMatrix} position={[2.281, 4.184, 2.723]} rotation={[0, -Math.PI / 2, 0]} />
      <instancedMesh args={[nodes.Balcony002.geometry, nodes.Balcony002.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony002.instanceMatrix} position={[2.281, 4.184, 4.754]} rotation={[0, -Math.PI / 2, 0]} />
      <instancedMesh args={[nodes.Window0210.geometry, nodes.Window0210.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0210.instanceMatrix} position={[3.737, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0220.geometry, nodes.Window0220.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0220.instanceMatrix} position={[3.737, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0230.geometry, nodes.Window0230.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0230.instanceMatrix} position={[2.024, 3.317, -2.508]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0240.geometry, nodes.Window0240.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0240.instanceMatrix} position={[2.024, 3.317, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0250.geometry, nodes.Window0250.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0250.instanceMatrix} position={[3.637, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0260.geometry, nodes.Window0260.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0260.instanceMatrix} position={[2.024, 7.506, -2.495]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0270.geometry, nodes.Window0270.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0270.instanceMatrix} position={[2.024, 7.506, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0280.geometry, nodes.Window0280.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0280.instanceMatrix} position={[3.637, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0290.geometry, nodes.Window0290.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0290.instanceMatrix} position={[5.418, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0300.geometry, nodes.Window0300.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0300.instanceMatrix} position={[7.186, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0310.geometry, nodes.Window0310.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0310.instanceMatrix} position={[5.423, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0320.geometry, nodes.Window0320.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0320.instanceMatrix} position={[7.228, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60060.geometry, nodes.Window60060.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60060.instanceMatrix} position={[7.204, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60070.geometry, nodes.Window60070.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60070.instanceMatrix} position={[5.418, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60080.geometry, nodes.Window60080.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60080.instanceMatrix} position={[3.636, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60090.geometry, nodes.Window60090.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60090.instanceMatrix} position={[2.09, 5.39, -4.368]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60100.geometry, nodes.Window60100.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60100.instanceMatrix} position={[2.09, 5.39, -2.493]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60110.geometry, nodes.Window60110.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60110.instanceMatrix} position={[3.635, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0010.geometry, nodes.Window0010.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0010.instanceMatrix} position={[-3.364, 7.511, 3.481]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0020.geometry, nodes.Window0020.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0020.instanceMatrix} position={[-3.364, 7.511, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0030.geometry, nodes.Window0030.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0030.instanceMatrix} position={[-3.364, 7.511, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0040.geometry, nodes.Window0040.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0040.instanceMatrix} position={[-3.364, 3.312, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0050.geometry, nodes.Window0050.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0050.instanceMatrix} position={[-3.364, 3.312, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0060.geometry, nodes.Window0060.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0060.instanceMatrix} position={[-3.364, 3.312, 3.483]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0070.geometry, nodes.Window0070.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0070.instanceMatrix} position={[-4.405, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0080.geometry, nodes.Window0080.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0080.instanceMatrix} position={[-6.288, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0090.geometry, nodes.Window0090.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0090.instanceMatrix} position={[-6.279, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0100.geometry, nodes.Window0100.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0100.instanceMatrix} position={[-4.404, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60010.geometry, nodes.Window60010.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60010.instanceMatrix} position={[-3.424, 5.393, 7.044]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60020.geometry, nodes.Window60020.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60020.instanceMatrix} position={[-3.424, 5.393, 5.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60030.geometry, nodes.Window60030.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60030.instanceMatrix} position={[-3.424, 5.393, 3.476]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60040.geometry, nodes.Window60040.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60040.instanceMatrix} position={[-4.408, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60050.geometry, nodes.Window60050.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60050.instanceMatrix} position={[-6.279, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0330.geometry, nodes.Window0330.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0330.instanceMatrix} position={[-6.283, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0340.geometry, nodes.Window0340.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0340.instanceMatrix} position={[-4.396, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0350.geometry, nodes.Window0350.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0350.instanceMatrix} position={[-6.283, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0360.geometry, nodes.Window0360.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0360.instanceMatrix} position={[-4.427, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60170.geometry, nodes.Window60170.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60170.instanceMatrix} position={[-6.298, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60180.geometry, nodes.Window60180.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60180.instanceMatrix} position={[-4.418, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60190.geometry, nodes.Window60190.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60190.instanceMatrix} position={[-7.278, 5.393, 7.044]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60200.geometry, nodes.Window60200.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60200.instanceMatrix} position={[-7.278, 5.393, 5.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60210.geometry, nodes.Window60210.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60210.instanceMatrix} position={[-7.278, 5.393, 3.476]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0370.geometry, nodes.Window0370.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0370.instanceMatrix} position={[-7.34, 7.511, 3.481]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0380.geometry, nodes.Window0380.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0380.instanceMatrix} position={[-7.34, 7.511, 5.253]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0390.geometry, nodes.Window0390.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0390.instanceMatrix} position={[-7.34, 7.511, 7.043]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0400.geometry, nodes.Window0400.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0400.instanceMatrix} position={[-7.376, 3.312, 3.483]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0110.geometry, nodes.Window0110.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0110.instanceMatrix} position={[-7.928, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0120.geometry, nodes.Window0120.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0120.instanceMatrix} position={[-6.144, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0130.geometry, nodes.Window0130.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0130.instanceMatrix} position={[-4.375, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0140.geometry, nodes.Window0140.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0140.instanceMatrix} position={[-4.375, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0150.geometry, nodes.Window0150.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0150.instanceMatrix} position={[-6.139, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0160.geometry, nodes.Window0160.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0160.instanceMatrix} position={[-7.929, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0170.geometry, nodes.Window0170.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0170.instanceMatrix} position={[-2.766, 3.311, -3.698]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0180.geometry, nodes.Window0180.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0180.instanceMatrix} position={[-2.766, 3.311, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0190.geometry, nodes.Window0190.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0190.instanceMatrix} position={[-2.766, 7.503, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0200.geometry, nodes.Window0200.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0200.instanceMatrix} position={[-2.766, 7.503, -3.699]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60120.geometry, nodes.Window60120.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60120.instanceMatrix} position={[-7.858, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60130.geometry, nodes.Window60130.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60130.instanceMatrix} position={[-6.154, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60140.geometry, nodes.Window60140.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60140.instanceMatrix} position={[-4.376, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60150.geometry, nodes.Window60150.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60150.instanceMatrix} position={[-2.821, 5.393, -3.681]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60160.geometry, nodes.Window60160.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60160.instanceMatrix} position={[-2.821, 5.393, -5.561]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0211.geometry, nodes.Window0211.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0211.instanceMatrix} position={[3.737, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0221.geometry, nodes.Window0221.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0221.instanceMatrix} position={[3.737, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0231.geometry, nodes.Window0231.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0231.instanceMatrix} position={[2.024, 3.317, -2.508]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0241.geometry, nodes.Window0241.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0241.instanceMatrix} position={[2.024, 3.317, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0251.geometry, nodes.Window0251.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0251.instanceMatrix} position={[3.637, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0261.geometry, nodes.Window0261.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0261.instanceMatrix} position={[2.024, 7.506, -2.495]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0271.geometry, nodes.Window0271.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0271.instanceMatrix} position={[2.024, 7.506, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0281.geometry, nodes.Window0281.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0281.instanceMatrix} position={[3.637, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0291.geometry, nodes.Window0291.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0291.instanceMatrix} position={[5.418, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0301.geometry, nodes.Window0301.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0301.instanceMatrix} position={[7.186, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0311.geometry, nodes.Window0311.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0311.instanceMatrix} position={[5.423, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0321.geometry, nodes.Window0321.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0321.instanceMatrix} position={[7.228, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0011.geometry, nodes.Window0011.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0011.instanceMatrix} position={[-3.364, 7.511, 3.481]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0021.geometry, nodes.Window0021.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0021.instanceMatrix} position={[-3.364, 7.511, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0031.geometry, nodes.Window0031.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0031.instanceMatrix} position={[-3.364, 7.511, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0041.geometry, nodes.Window0041.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0041.instanceMatrix} position={[-3.364, 3.312, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0051.geometry, nodes.Window0051.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0051.instanceMatrix} position={[-3.364, 3.312, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0061.geometry, nodes.Window0061.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0061.instanceMatrix} position={[-3.364, 3.312, 3.483]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0071.geometry, nodes.Window0071.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0071.instanceMatrix} position={[-4.405, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0081.geometry, nodes.Window0081.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0081.instanceMatrix} position={[-6.288, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0091.geometry, nodes.Window0091.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0091.instanceMatrix} position={[-6.279, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0101.geometry, nodes.Window0101.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0101.instanceMatrix} position={[-4.404, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0331.geometry, nodes.Window0331.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0331.instanceMatrix} position={[-6.283, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0341.geometry, nodes.Window0341.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0341.instanceMatrix} position={[-4.396, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0351.geometry, nodes.Window0351.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0351.instanceMatrix} position={[-6.283, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0361.geometry, nodes.Window0361.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0361.instanceMatrix} position={[-4.427, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0371.geometry, nodes.Window0371.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0371.instanceMatrix} position={[-7.34, 7.511, 3.481]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0381.geometry, nodes.Window0381.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0381.instanceMatrix} position={[-7.34, 7.511, 5.253]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0391.geometry, nodes.Window0391.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0391.instanceMatrix} position={[-7.34, 7.511, 7.043]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0401.geometry, nodes.Window0401.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0401.instanceMatrix} position={[-7.376, 3.312, 3.483]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0111.geometry, nodes.Window0111.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0111.instanceMatrix} position={[-7.928, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0121.geometry, nodes.Window0121.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0121.instanceMatrix} position={[-6.144, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0131.geometry, nodes.Window0131.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0131.instanceMatrix} position={[-4.375, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0141.geometry, nodes.Window0141.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0141.instanceMatrix} position={[-4.375, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0151.geometry, nodes.Window0151.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0151.instanceMatrix} position={[-6.139, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0161.geometry, nodes.Window0161.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0161.instanceMatrix} position={[-7.929, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0171.geometry, nodes.Window0171.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0171.instanceMatrix} position={[-2.766, 3.311, -3.698]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0181.geometry, nodes.Window0181.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0181.instanceMatrix} position={[-2.766, 3.311, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0191.geometry, nodes.Window0191.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0191.instanceMatrix} position={[-2.766, 7.503, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0201.geometry, nodes.Window0201.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0201.instanceMatrix} position={[-2.766, 7.503, -3.699]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60061.geometry, nodes.Window60061.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60061.instanceMatrix} position={[7.204, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60071.geometry, nodes.Window60071.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60071.instanceMatrix} position={[5.418, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60081.geometry, nodes.Window60081.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60081.instanceMatrix} position={[3.636, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60091.geometry, nodes.Window60091.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60091.instanceMatrix} position={[2.09, 5.39, -4.368]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60101.geometry, nodes.Window60101.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60101.instanceMatrix} position={[2.09, 5.39, -2.493]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60111.geometry, nodes.Window60111.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60111.instanceMatrix} position={[3.635, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60011.geometry, nodes.Window60011.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60011.instanceMatrix} position={[-3.424, 5.393, 7.044]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60021.geometry, nodes.Window60021.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60021.instanceMatrix} position={[-3.424, 5.393, 5.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60031.geometry, nodes.Window60031.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60031.instanceMatrix} position={[-3.424, 5.393, 3.476]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60041.geometry, nodes.Window60041.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60041.instanceMatrix} position={[-4.408, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60051.geometry, nodes.Window60051.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60051.instanceMatrix} position={[-6.279, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60171.geometry, nodes.Window60171.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60171.instanceMatrix} position={[-6.298, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60181.geometry, nodes.Window60181.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60181.instanceMatrix} position={[-4.418, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60191.geometry, nodes.Window60191.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60191.instanceMatrix} position={[-7.278, 5.393, 7.044]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60201.geometry, nodes.Window60201.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60201.instanceMatrix} position={[-7.278, 5.393, 5.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60211.geometry, nodes.Window60211.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60211.instanceMatrix} position={[-7.278, 5.393, 3.476]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60121.geometry, nodes.Window60121.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60121.instanceMatrix} position={[-7.858, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60131.geometry, nodes.Window60131.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60131.instanceMatrix} position={[-6.154, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60141.geometry, nodes.Window60141.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60141.instanceMatrix} position={[-4.376, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60151.geometry, nodes.Window60151.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60151.instanceMatrix} position={[-2.821, 5.393, -3.681]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60161.geometry, nodes.Window60161.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60161.instanceMatrix} position={[-2.821, 5.393, -5.561]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/assets/venice-transformed.glb')
