/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/venice.glb --root=./public --output=public/assets/model.jsx --shadows --transform --keepmeshes --console 
Files: public/assets/venice.glb [9.33MB] > /home/luca/venezia-website/public/assets/venice-transformed.glb [910.91KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/venice-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.MS_Disney_Wish_19.geometry} material={nodes.MS_Disney_Wish_19.material} position={[-26.036, -0.765, 53.919]} rotation={[Math.PI, 0, Math.PI]} scale={0.531} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-12.485, 5.498, 17.294]} rotation={[-Math.PI / 2, 0, -0.207]} scale={0.751} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge.geometry} material={nodes.Bridge.material} />
      <mesh castShadow receiveShadow geometry={nodes.Pole001.geometry} material={nodes.Pole001.material} position={[-3.017, 0.729, -2.636]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole002.geometry} material={nodes.Pole002.material} position={[-3.017, 0.729, -0.958]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole003.geometry} material={nodes.Pole003.material} position={[-3.017, 0.729, -1.816]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole004.geometry} material={nodes.Pole004.material} position={[-3.017, 0.729, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole005.geometry} material={nodes.Pole005.material} position={[-3.017, 0.729, 2.077]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole006.geometry} material={nodes.Pole006.material} position={[-2.828, 0.797, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole007.geometry} material={nodes.Pole007.material} position={[-0.738, 1.319, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole008.geometry} material={nodes.Pole008.material} position={[0.723, 1.319, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole009.geometry} material={nodes.Pole009.material} position={[2.648, 0.776, 1.062]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole010.geometry} material={nodes.Pole010.material} position={[2.648, 0.776, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole011.geometry} material={nodes.Pole011.material} position={[0.721, 1.317, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole012.geometry} material={nodes.Pole012.material} position={[-0.754, 1.317, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole013.geometry} material={nodes.Pole013.material} position={[-2.831, 0.78, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole014.geometry} material={nodes.Pole014.material} position={[-1.404, 1.154, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole015.geometry} material={nodes.Pole015.material} position={[1.357, 1.135, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole016.geometry} material={nodes.Pole016.material} position={[1.358, 1.136, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole017.geometry} material={nodes.Pole017.material} position={[-0.002, 1.304, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole018.geometry} material={nodes.Pole018.material} position={[-0.002, 1.304, -0.98]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole019.geometry} material={nodes.Pole019.material} position={[2.063, 0.934, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole020.geometry} material={nodes.Pole020.material} position={[2.065, 0.938, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole021.geometry} material={nodes.Pole021.material} position={[-2.137, 0.957, -0.986]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole022.geometry} material={nodes.Pole022.material} position={[-2.137, 0.957, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole023.geometry} material={nodes.Pole023.material} position={[-1.401, 1.154, 1.05]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole024.geometry} material={nodes.Pole024.material} position={[-3.258, 0.728, 8.902]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole025.geometry} material={nodes.Pole025.material} position={[-3.279, 0.728, 9.923]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole028.geometry} material={nodes.Pole028.material} position={[-2.93, 0.728, 9.423]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole026.geometry} material={nodes.Pole026.material} position={[-4.553, 2.362, 18.545]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole027.geometry} material={nodes.Pole027.material} position={[-5.304, 2.362, 18.529]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole029.geometry} material={nodes.Pole029.material} position={[-6.073, 2.362, 18.551]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole030.geometry} material={nodes.Pole030.material} position={[-4.398, 2.362, 17.976]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole031.geometry} material={nodes.Pole031.material} position={[-4.215, 2.362, 17.271]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole032.geometry} material={nodes.Pole032.material} position={[-4.06, 2.362, 16.602]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole033.geometry} material={nodes.Pole033.material} position={[-3.87, 2.362, 15.92]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole034.geometry} material={nodes.Pole034.material} position={[-3.724, 2.362, 15.27]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Pole035.geometry} material={nodes.Pole035.material} position={[-3.567, 2.362, 14.613]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.Building_1.geometry} material={nodes.Building_1.material} position={[5.535, 0.009, -3.518]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver013.geometry} material={nodes.Power_Line_Receiver013.material} position={[1.681, 6.913, -5.148]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver014.geometry} material={nodes.Power_Line_Receiver014.material} position={[1.606, 6.368, -5.15]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver015.geometry} material={nodes.Power_Line_Receiver015.material} position={[1.502, 6.368, -5.143]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver016.geometry} material={nodes.Power_Line_Receiver016.material} position={[1.746, 4.535, -1.794]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver017.geometry} material={nodes.Power_Line_Receiver017.material} position={[1.75, 4.432, -1.605]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver018.geometry} material={nodes.Power_Line_Receiver018.material} position={[1.746, 4.332, -1.801]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver007.geometry} material={nodes.Power_Line_Receiver007.material} position={[-3.629, 6.913, 1.519]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver008.geometry} material={nodes.Power_Line_Receiver008.material} position={[-3.632, 6.363, 1.453]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver009.geometry} material={nodes.Power_Line_Receiver009.material} position={[-3.632, 6.363, 1.34]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver010.geometry} material={nodes.Power_Line_Receiver010.material} position={[-6.981, 4.533, 1.591]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver011.geometry} material={nodes.Power_Line_Receiver011.material} position={[-6.98, 4.331, 1.591]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver012.geometry} material={nodes.Power_Line_Receiver012.material} position={[-7.167, 4.432, 1.593]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver001.geometry} material={nodes.Power_Line_Receiver001.material} position={[-2.412, 6.911, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver002.geometry} material={nodes.Power_Line_Receiver002.material} position={[-2.226, 6.366, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver003.geometry} material={nodes.Power_Line_Receiver003.material} position={[-2.342, 6.366, -2.913]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver004.geometry} material={nodes.Power_Line_Receiver004.material} position={[-2.475, 4.534, -6.269]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver005.geometry} material={nodes.Power_Line_Receiver005.material} position={[-2.486, 4.431, -6.454]} />
      <mesh castShadow receiveShadow geometry={nodes.Power_Line_Receiver006.geometry} material={nodes.Power_Line_Receiver006.material} position={[-2.479, 4.331, -6.273]} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Box001.geometry} material={nodes.Flower_Box001.material} position={[1.944, 4.629, -2.487]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Box002.geometry} material={nodes.Flower_Box002.material} position={[1.944, 4.629, -4.35]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox001.geometry} material={nodes.FlowerBox001.material} position={[-4.394, 4.632, 1.791]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox002.geometry} material={nodes.FlowerBox002.material} position={[-6.299, 4.632, 1.791]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox003.geometry} material={nodes.FlowerBox003.material} position={[-10.217, 6.176, 6.422]} rotation={[1.57, 0, 3.141]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox004.geometry} material={nodes.FlowerBox004.material} position={[-11.266, 6.176, 6.422]} rotation={[1.57, 0, 3.141]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox005.geometry} material={nodes.FlowerBox005.material} position={[-11.266, 6.177, 8.898]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox006.geometry} material={nodes.FlowerBox006.material} position={[-10.216, 6.177, 8.898]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox007.geometry} material={nodes.FlowerBox007.material} position={[-9.072, 1.128, 8.806]} rotation={[0.49, 1.244, 0.926]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox008.geometry} material={nodes.FlowerBox008.material} position={[-8.927, 1.13, 8.805]} rotation={[0.49, 1.244, 0.926]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox009.geometry} material={nodes.FlowerBox009.material} position={[-8.676, 1.118, 8.941]} rotation={[3.03, -0.023, -1.859]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox010.geometry} material={nodes.FlowerBox010.material} position={[-11.364, 0.71, 10.043]} rotation={[1.775, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox011.geometry} material={nodes.FlowerBox011.material} position={[-10.487, 0.7, 10.041]} rotation={[1.775, -0.001, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox012.geometry} material={nodes.FlowerBox012.material} position={[-9.591, 0.71, 10.043]} rotation={[1.775, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox013.geometry} material={nodes.FlowerBox013.material} position={[-7.385, 0.704, 10.042]} rotation={[1.768, 0.003, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox014.geometry} material={nodes.FlowerBox014.material} position={[-6.493, 0.71, 10.043]} rotation={[1.777, -0.002, 0.005]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox015.geometry} material={nodes.FlowerBox015.material} position={[-5.594, 0.71, 10.043]} rotation={[1.774, 0.006, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox016.geometry} material={nodes.FlowerBox016.material} position={[-4.782, 0.47, 10.047]} rotation={[1.814, 0.86, -0.221]} />
      <mesh castShadow receiveShadow geometry={nodes.FlowerBox017.geometry} material={nodes.FlowerBox017.material} position={[-3.796, 0.71, 10.043]} rotation={[1.775, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket001.geometry} material={nodes.Wall_Bracket001.material} position={[1.933, 6.469, -3.486]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket003.geometry} material={nodes.Wall_Bracket003.material} position={[-5.37, 6.492, 1.791]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket004.geometry} material={nodes.Wall_Bracket004.material} position={[-5.37, 6.492, 8.914]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.Wall_Bracket002.geometry} material={nodes.Wall_Bracket002.material} position={[-2.671, 6.483, -4.62]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket001.geometry} material={nodes.WallBracket001.material} position={[-10.867, 5.614, 6.405]} rotation={[-1.571, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket003.geometry} material={nodes.WallBracket003.material} position={[-10.954, 4.644, 6.405]} rotation={[-1.571, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket002.geometry} material={nodes.WallBracket002.material} position={[-11.036, 4.613, 17.291]} rotation={[-Math.PI / 2, 0, -0.21]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket004.geometry} material={nodes.WallBracket004.material} position={[-13.77, 4.585, 16.706]} rotation={[-1.577, -0.028, -0.21]} />
      <mesh castShadow receiveShadow geometry={nodes.WallBracket005.geometry} material={nodes.WallBracket005.material} position={[-14.874, 3.462, 16.75]} rotation={[-1.565, 0.026, -0.21]} scale={0.847} />
      <mesh castShadow receiveShadow geometry={nodes.Building_2.geometry} material={nodes.Building_2.material} position={[3.321, 5.83, 3.377]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3001.geometry} material={nodes.Window3001.material} position={[2.522, 8.207, 2.725]} rotation={[Math.PI / 2, 0, 1.569]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3002.geometry} material={nodes.Window3002.material} position={[2.522, 8.207, 4.729]} rotation={[Math.PI / 2, 0, 1.569]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3004.geometry} material={nodes.Window3004.material} position={[-11.326, 4.371, 8.851]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3005.geometry} material={nodes.Window3005.material} position={[-10.241, 4.371, 8.851]} rotation={[1.571, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Window3003.geometry} material={nodes.Window3003.material} position={[-12.331, 4.371, 7.667]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_2002.geometry} material={nodes.Building_2002.material} position={[2.479, 1.267, 4.748]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3.geometry} material={nodes.Building_3.material} position={[4.958, -0.015, 8.769]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3001.geometry} material={nodes.Building_3001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3002.geometry} material={nodes.Building_3002.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_3003.geometry} material={nodes.Building_3003.material} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4.geometry} material={nodes.Building_4.material} position={[-5.471, 0.009, 5.57]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4001.geometry} material={nodes.Building_4001.material} position={[-5.471, 0.009, 5.57]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-7.377, 2.218, 7.493]} rotation={[0, -0.116, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_5.geometry} material={nodes.Building_5.material} position={[-6.268, 0.001, -4.598]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_6.geometry} material={nodes.Building_6.material} position={[-1.434, 5.07, -9.805]} />
      <mesh castShadow receiveShadow geometry={nodes.Rooftop_AC.geometry} material={nodes.Rooftop_AC.material} position={[-5.682, 9.525, -9.877]} />
      <mesh castShadow receiveShadow geometry={nodes.Rooftop_Access.geometry} material={nodes.Rooftop_Access.material} position={[-4.327, 9.524, -14.467]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_7.geometry} material={nodes.Building_7.material} position={[3.953, -0.009, -11.862]} />
      <mesh castShadow receiveShadow geometry={nodes.WestPlaza.geometry} material={nodes.WestPlaza.material} position={[-13.293, -0.887, 2.8]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard.geometry} material={nodes.AdBoard.material} position={[-13.488, 0.7, 4.448]} rotation={[0, -1.554, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard001.geometry} material={nodes.AdBoard001.material} position={[5.7, 0.788, 13.504]} rotation={[0, -0.255, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.AdBoard002.geometry} material={nodes.AdBoard002.material} position={[5.7, 0.788, 13.504]} rotation={[0, -0.255, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge001.geometry} material={nodes.Bridge001.material} position={[-8.138, 1.41, 4.178]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge002.geometry} material={nodes.Bridge002.material} position={[-9.434, 1.965, 5.271]} rotation={[0, 0.006, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge003.geometry} material={nodes.Bridge003.material} position={[-9.426, 2.116, 5.608]} rotation={[0.003, 0.032, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge004.geometry} material={nodes.Bridge004.material} position={[-9.436, 1.816, 4.924]} rotation={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge005.geometry} material={nodes.Bridge005.material} position={[-9.44, 1.665, 4.58]} rotation={[0.001, 0.002, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge006.geometry} material={nodes.Bridge006.material} position={[-9.434, 1.513, 4.242]} rotation={[0.003, -0.004, -0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge007.geometry} material={nodes.Bridge007.material} position={[-9.434, 1.362, 3.903]} rotation={[-0.001, 0.001, 0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge008.geometry} material={nodes.Bridge008.material} position={[-9.434, 1.213, 3.564]} rotation={[0.001, 0.001, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge009.geometry} material={nodes.Bridge009.material} position={[-9.434, 1.062, 3.226]} rotation={[0.001, 0.003, 0.001]} />
      <mesh castShadow receiveShadow geometry={nodes.Bridge010.geometry} material={nodes.Bridge010.material} position={[-9.434, 0.913, 2.906]} rotation={[-0.003, -0.001, 0.003]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1001.geometry} material={nodes.WoodenPlank1001.material} position={[-7.387, 1.35, 3.706]} rotation={[-0.416, 0.037, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1002.geometry} material={nodes.WoodenPlank1002.material} position={[-7.364, 1.505, 4.001]} rotation={[-0.416, 0.008, 0.006]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1003.geometry} material={nodes.WoodenPlank1003.material} position={[-11.397, 6.188, 7.924]} rotation={[-0.39, -1.118, -0.357]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1004.geometry} material={nodes.WoodenPlank1004.material} position={[-12.298, 1.938, 8.266]} rotation={[-1.57, 0.059, 1.563]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1005.geometry} material={nodes.WoodenPlank1005.material} position={[-12.322, 1.933, 8.405]} rotation={[-1.57, 0.09, 1.563]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1010.geometry} material={nodes.WoodenPlank1010.material} position={[-9.229, 4.545, 7.628]} rotation={[0.361, 0, -1.571]} scale={0.77} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1011.geometry} material={nodes.WoodenPlank1011.material} position={[-9.211, 4.945, 7.826]} rotation={[2.261, -0.004, -1.574]} scale={0.77} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1012.geometry} material={nodes.WoodenPlank1012.material} position={[-10.9, 5.005, 8.955]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1013.geometry} material={nodes.WoodenPlank1013.material} position={[-10.9, 5.031, 8.955]} rotation={[0, -1.55, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1006.geometry} material={nodes.WoodenPlank1006.material} position={[-12.301, 0.786, 7.851]} rotation={[0, 0, 1.236]} scale={[1, 1, 0.889]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1007.geometry} material={nodes.WoodenPlank1007.material} position={[-12.248, 0.893, 7.967]} rotation={[0, 0, 1.483]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1008.geometry} material={nodes.WoodenPlank1008.material} position={[-12.339, 0.802, 7.967]} rotation={[0, 0, 1.483]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1009.geometry} material={nodes.WoodenPlank1009.material} position={[-12.288, 0.91, 7.946]} rotation={[0, 0, 1.214]} scale={[1, 1, 0.722]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1019.geometry} material={nodes.WoodenPlank1019.material} position={[-8.532, 6.678, 7.4]} rotation={[1.134, -1.163, 1.143]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1020.geometry} material={nodes.WoodenPlank1020.material} position={[-8.547, 6.688, 7.269]} rotation={[1.448, -1.171, 1.478]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1017.geometry} material={nodes.WoodenPlank1017.material} position={[-8.932, 2.405, 10.925]} rotation={[-3.037, -1.258, 0.124]} scale={0.519} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1018.geometry} material={nodes.WoodenPlank1018.material} position={[-8.881, 2.41, 10.82]} rotation={[-3.063, -1.337, 0.098]} scale={0.519} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1016.geometry} material={nodes.WoodenPlank1016.material} position={[-5.966, 1.762, 20.581]} rotation={[1.667, -0.045, 3.13]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1014.geometry} material={nodes.WoodenPlank1014.material} position={[-3.99, 0.6, 20.29]} rotation={[0, 1.068, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenPlank1015.geometry} material={nodes.WoodenPlank1015.material} position={[-1.9, 0.548, 21.029]} rotation={[0.468, 1.395, -0.466]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-7.594, 2.197, 7.075]} rotation={[0, -0.131, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Building_4002.geometry} material={nodes.Building_4002.material} position={[-10.805, 7.727, 7.075]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-9.628, 4.806, 6.397]} />
      <mesh castShadow receiveShadow geometry={nodes.Tower.geometry} material={nodes.Tower.material} position={[-10.819, 0.792, 7.653]} />
      <mesh castShadow receiveShadow geometry={nodes.CanalStairs.geometry} material={nodes.CanalStairs.material} position={[-12.674, 0.395, 9.443]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-17.273, -0.495, 12.389]} rotation={[-0.076, 1.016, 0.008]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod004.geometry} material={nodes.WoodenRod004.material} position={[-2.294, -0.407, 23.526]} rotation={[0.144, -1.312, 0.085]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod005.geometry} material={nodes.WoodenRod005.material} position={[-4.53, -0.396, 26.334]} rotation={[-0.616, -1.325, -0.573]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod006.geometry} material={nodes.WoodenRod006.material} position={[-4.4, -0.312, 27.439]} rotation={[-0.056, -1.26, -0.029]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[-17.151, -0.576, 11.041]} rotation={[0.058, 1.006, -0.017]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod016.geometry} material={nodes.WoodenRod016.material} position={[2.515, -0.396, 30.757]} rotation={[1.207, -1.502, 1.246]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod017.geometry} material={nodes.WoodenRod017.material} position={[2.493, -0.741, 31.283]} rotation={[-0.056, -1.26, -0.029]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod001.geometry} material={nodes.WoodenRod001.material} position={[-3.335, -1.204, 20.555]} rotation={[0.134, -0.082, -0.081]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod002.geometry} material={nodes.WoodenRod002.material} position={[-3.855, -1.111, 20.273]} rotation={[0.024, 0.021, -0.068]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod003.geometry} material={nodes.WoodenRod003.material} position={[-4.294, -0.287, 20.872]} rotation={[0.144, -1.312, 0.085]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod007.geometry} material={nodes.WoodenRod007.material} position={[-2.844, -0.862, 20.716]} rotation={[0.018, 0.086, 0.086]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod008.geometry} material={nodes.WoodenRod008.material} position={[1.003, -10.76, 25.299]} rotation={[0.043, -0.62, -0.007]} scale={[3.611, 6.176, 3.611]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod009.geometry} material={nodes.WoodenRod009.material} position={[1.544, -0.704, 24.595]} rotation={[2.775, -1.474, 2.745]} scale={[3.611, 0.692, 3.611]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod010.geometry} material={nodes.WoodenRod010.material} position={[1.884, -0.832, 23.476]} rotation={[0.03, 0.017, -0.083]} scale={[3.611, 0.813, 3.611]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod011.geometry} material={nodes.WoodenRod011.material} position={[0.634, 0.178, 27.115]} rotation={[0.09, 1.231, 3.062]} scale={[3.531, 0.594, 3.531]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod012.geometry} material={nodes.WoodenRod012.material} position={[0.138, -8.602, 27.981]} rotation={[0.043, -0.62, -0.007]} scale={[2.849, 4.873, 2.849]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod013.geometry} material={nodes.WoodenRod013.material} position={[-0.246, -0.664, 29.687]} rotation={[2.775, -1.474, 2.745]} scale={[2.443, 0.468, 2.443]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod014.geometry} material={nodes.WoodenRod014.material} position={[-0.594, -0.649, 31.336]} rotation={[-3.107, -0.07, 2.991]} scale={[2.338, 0.448, 2.338]} />
      <mesh castShadow receiveShadow geometry={nodes.WoodenRod015.geometry} material={nodes.WoodenRod015.material} position={[-1.123, -5.648, 32.546]} rotation={[0.043, -0.62, -0.007]} scale={[1.865, 3.191, 1.865]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} position={[-8.431, 2.159, 10.835]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-11.399, 0.66, 10.154]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-9.641, 0.66, 10.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-7.416, 0.66, 10.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031.geometry} material={nodes.Cube031.material} position={[-6.537, 0.656, 10.147]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} position={[-5.638, 0.658, 10.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} position={[-3.837, 0.66, 10.153]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-10.535, 0.65, 10.15]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} position={[-9.739, 1.671, 14.229]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} position={[-8.692, 0.665, 16.425]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-11.08, 6.626, 17.415]} rotation={[0, -0.212, 0]} scale={0.826} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-13.787, 6.626, 16.838]} rotation={[0, -0.216, 0]} scale={0.826} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-12.591, 7.717, 17.568]} rotation={[0, -0.198, 0]} scale={0.826} />
      <mesh castShadow receiveShadow geometry={nodes.RoundWindow002.geometry} material={nodes.RoundWindow002.material} position={[-10.105, 4.118, 17.822]} rotation={[Math.PI, -1.349, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.RoundWindow003.geometry} material={nodes.RoundWindow003.material} position={[-14.881, 4.145, 16.804]} rotation={[3.141, -1.373, -1.574]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-12.465, 1.671, 17.252]} rotation={[0, -0.21, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-10.074, 2.67, 17.761]} rotation={[0, -0.209, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Foundation.geometry} material={nodes.Foundation.material} position={[5.06, 0.388, 17.44]} rotation={[0, -0.436, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[7.822, 0.388, 6.72]} />
      <mesh castShadow receiveShadow geometry={nodes.BestKeptSecret.geometry} material={nodes.BestKeptSecret.material} position={[3.206, 0.734, 18.254]} />
      <mesh castShadow receiveShadow geometry={nodes.Beach.geometry} material={nodes.Beach.material} position={[1.147, 0.268, 23.878]} rotation={[0, -0.286, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock.geometry} material={nodes.Rock.material} position={[2.321, 0.329, 23.329]} scale={0.818} />
      <mesh castShadow receiveShadow geometry={nodes.Rock001.geometry} material={nodes.Rock001.material} position={[2.11, 0.329, 23.179]} rotation={[0.286, 0.199, 1.214]} scale={0.818} />
      <mesh castShadow receiveShadow geometry={nodes.Rock002.geometry} material={nodes.Rock002.material} position={[2.17, 0.387, 22.986]} rotation={[0.286, 0.199, 1.214]} scale={0.818} />
      <mesh castShadow receiveShadow geometry={nodes.Rock003.geometry} material={nodes.Rock003.material} position={[2.316, 0.387, 22.945]} rotation={[-0.239, -0.082, -1.597]} scale={0.818} />
      <mesh castShadow receiveShadow geometry={nodes.Rock004.geometry} material={nodes.Rock004.material} position={[1.993, 0.4, 22.598]} rotation={[1.134, -0.909, -0.049]} scale={0.818} />
      <mesh castShadow receiveShadow geometry={nodes.Rock005.geometry} material={nodes.Rock005.material} position={[2.165, 0.314, 23.596]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock006.geometry} material={nodes.Rock006.material} position={[1.478, 0.227, 24.236]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock007.geometry} material={nodes.Rock007.material} position={[1.527, 0.323, 24.071]} rotation={[0.863, -0.424, -0.875]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock008.geometry} material={nodes.Rock008.material} position={[1.692, 0.386, 23.841]} rotation={[-0.032, -0.126, 1.992]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock009.geometry} material={nodes.Rock009.material} position={[1.711, 0.32, 23.643]} rotation={[1.633, 1.199, -1.196]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock010.geometry} material={nodes.Rock010.material} position={[2.014, 0.403, 23.779]} rotation={[2.748, 0.548, -1.302]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock011.geometry} material={nodes.Rock011.material} position={[1.952, 0.47, 23.819]} rotation={[-2.812, 0.014, 0.296]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock012.geometry} material={nodes.Rock012.material} position={[1.767, 0.092, 23.906]} rotation={[-2.917, 0.115, 2.983]} scale={1.188} />
      <mesh castShadow receiveShadow geometry={nodes.Rock013.geometry} material={nodes.Rock013.material} position={[1.712, 0.231, 24.158]} rotation={[2.892, 1.037, -1.922]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock014.geometry} material={nodes.Rock014.material} position={[1.972, 0.281, 23.921]} rotation={[-2.69, 0.833, 2.967]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock015.geometry} material={nodes.Rock015.material} position={[0.379, 0.144, 24.427]} rotation={[-0.13, -0.988, -0.545]} scale={0.241} />
      <mesh castShadow receiveShadow geometry={nodes.Rock016.geometry} material={nodes.Rock016.material} position={[3.225, 0.367, 24.427]} rotation={[3.055, -0.343, 2.668]} scale={[0.374, 0.279, 0.397]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock017.geometry} material={nodes.Rock017.material} position={[0.436, -0.092, 26.558]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock018.geometry} material={nodes.Rock018.material} position={[0.486, 0.004, 26.393]} rotation={[0.863, -0.424, -0.875]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock019.geometry} material={nodes.Rock019.material} position={[0.911, 0.151, 26.141]} rotation={[-2.812, 0.014, 0.296]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock020.geometry} material={nodes.Rock020.material} position={[0.725, -0.227, 26.228]} rotation={[-2.917, 0.115, 2.983]} scale={1.188} />
      <mesh castShadow receiveShadow geometry={nodes.Rock021.geometry} material={nodes.Rock021.material} position={[0.671, -0.088, 26.479]} rotation={[2.892, 1.037, -1.922]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock022.geometry} material={nodes.Rock022.material} position={[0.621, -0.186, 27.108]} rotation={[0.336, -1.413, 2.789]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock023.geometry} material={nodes.Rock023.material} position={[0.772, -0.221, 26.985]} rotation={[-0.284, -0.509, 1.148]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock024.geometry} material={nodes.Rock024.material} position={[0.951, -0.053, 26.532]} rotation={[2.646, 1.155, -1.683]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock025.geometry} material={nodes.Rock025.material} position={[0.912, 0.118, 26.924]} rotation={[3.011, 1.188, 0.66]} scale={1.188} />
      <mesh castShadow receiveShadow geometry={nodes.Rock026.geometry} material={nodes.Rock026.material} position={[0.664, -0.037, 26.916]} rotation={[-2.343, 0.376, 1.012]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock027.geometry} material={nodes.Rock027.material} position={[0.958, -0.069, 26.293]} rotation={[2.524, 1.193, -2.403]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock028.geometry} material={nodes.Rock028.material} position={[1.173, 0.128, 26.038]} rotation={[0.292, -0.932, -3.005]} scale={0.591} />
      <mesh castShadow receiveShadow geometry={nodes.Rock029.geometry} material={nodes.Rock029.material} position={[0.776, -0.017, 25.871]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock030.geometry} material={nodes.Rock030.material} position={[0.239, -0.369, 27.283]} rotation={[-3.02, -0.146, -2.846]} scale={[2.304, 1.335, 2.358]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock031.geometry} material={nodes.Rock031.material} position={[0.563, -0.431, 27.726]} rotation={[-2.252, 0.576, 1.301]} scale={[2.304, 1.335, 2.358]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock032.geometry} material={nodes.Rock032.material} position={[0.798, -0.117, 27.174]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock033.geometry} material={nodes.Rock033.material} position={[0.394, -0.074, 26.788]} rotation={[-0.046, -1.058, 0.072]} scale={[0.983, 0.425, 1.441]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock034.geometry} material={nodes.Rock034.material} position={[0.445, -0.044, 27.034]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock035.geometry} material={nodes.Rock035.material} position={[1.244, -0.304, 25.284]} rotation={[-2.032, 0.936, 1.491]} scale={[2.304, 1.335, 2.358]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock036.geometry} material={nodes.Rock036.material} position={[0.216, -0.334, 27.901]} rotation={[-0.054, -0.207, -2.101]} scale={[2.304, 1.335, 2.358]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock037.geometry} material={nodes.Rock037.material} position={[0.204, -0.1, 27.515]} rotation={[-0.046, -1.058, 0.072]} scale={[0.983, 0.425, 1.441]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock038.geometry} material={nodes.Rock038.material} position={[0.566, 0.072, 27.324]} rotation={[0.139, -0.37, 3.08]} scale={0.374} />
      <mesh castShadow receiveShadow geometry={nodes.Rock039.geometry} material={nodes.Rock039.material} position={[0.165, -0.26, 27.955]} rotation={[0.044, 1.262, 0.059]} scale={[1.141, 1.187, 0.578]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock040.geometry} material={nodes.Rock040.material} position={[0.261, -0.092, 28.133]} rotation={[-2.66, -0.618, -3.134]} scale={[1.233, 0.432, 0.672]} />
      <mesh castShadow receiveShadow geometry={nodes.Rock041.geometry} material={nodes.Rock041.material} position={[-0.32, 0.058, 29.698]} rotation={[3.011, 1.188, 0.66]} scale={1.188} />
      <mesh castShadow receiveShadow geometry={nodes.Rock042.geometry} material={nodes.Rock042.material} position={[-0.205, -0.117, 29.873]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.Rock043.geometry} material={nodes.Rock043.material} position={[-1.027, -0.052, 31.606]} rotation={[-1.16, 0.76, -0.598]} scale={0.453} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance.geometry} material={nodes.GN_Instance.material} position={[1.999, 3.751, -5.214]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_37.geometry} material={nodes.GN_Instance_37.material} position={[2.447, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_40.geometry} material={nodes.GN_Instance_40.material} position={[-3.552, 3.808, 1.796]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_58.geometry} material={nodes.GN_Instance_58.material} position={[-3.734, 4.222, 8.903]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_89.geometry} material={nodes.GN_Instance_89.material} position={[-11.615, 2.901, 8.738]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_1.geometry} material={nodes.GN_Instance_1.material} position={[0.873, 4.291, -5.214]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_38.geometry} material={nodes.GN_Instance_38.material} position={[1.197, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_41.geometry} material={nodes.GN_Instance_41.material} position={[-3.552, 4.318, 0.733]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_59.geometry} material={nodes.GN_Instance_59.material} position={[-3.734, 4.431, 10.135]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_90.geometry} material={nodes.GN_Instance_90.material} position={[-11.613, 3.71, 9.688]} rotation={[0, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_2.geometry} material={nodes.GN_Instance_2.material} position={[1.917, 3.786, -5.214]} rotation={[-Math.PI / 2, -1.12, -Math.PI / 2]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_39.geometry} material={nodes.GN_Instance_39.material} position={[2.357, 4.231, 1.86]} rotation={[0.002, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_42.geometry} material={nodes.GN_Instance_42.material} position={[-3.552, 3.812, 1.777]} rotation={[-2.691, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_60.geometry} material={nodes.GN_Instance_60.material} position={[-3.734, 4.235, 8.992]} rotation={[-0.17, 0, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_91.geometry} material={nodes.GN_Instance_91.material} position={[-11.615, 2.954, 8.809]} rotation={[-0.711, 0.001, -0.002]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_3.geometry} material={nodes.GN_Instance_3.material} position={[3.737, 7.497, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_4.geometry} material={nodes.GN_Instance_4.material} position={[3.737, 3.317, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_5.geometry} material={nodes.GN_Instance_5.material} position={[2.024, 3.317, -2.508]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_6.geometry} material={nodes.GN_Instance_6.material} position={[2.024, 3.317, -4.371]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_7.geometry} material={nodes.GN_Instance_7.material} position={[3.637, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_8.geometry} material={nodes.GN_Instance_8.material} position={[2.024, 7.506, -2.495]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_9.geometry} material={nodes.GN_Instance_9.material} position={[2.024, 7.506, -4.371]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_10.geometry} material={nodes.GN_Instance_10.material} position={[3.637, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_11.geometry} material={nodes.GN_Instance_11.material} position={[5.418, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_12.geometry} material={nodes.GN_Instance_12.material} position={[7.186, 7.506, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_13.geometry} material={nodes.GN_Instance_13.material} position={[5.423, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_14.geometry} material={nodes.GN_Instance_14.material} position={[7.228, 3.324, -5.425]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_21.geometry} material={nodes.GN_Instance_21.material} position={[5.444, 7.497, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_22.geometry} material={nodes.GN_Instance_22.material} position={[7.198, 7.497, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_25.geometry} material={nodes.GN_Instance_25.material} position={[5.432, 3.317, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_26.geometry} material={nodes.GN_Instance_26.material} position={[7.206, 3.317, -1.446]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_27.geometry} material={nodes.GN_Instance_27.material} position={[8.982, 3.317, -2.508]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_28.geometry} material={nodes.GN_Instance_28.material} position={[8.982, 3.317, -4.379]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_30.geometry} material={nodes.GN_Instance_30.material} position={[8.986, 7.506, -2.495]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_31.geometry} material={nodes.GN_Instance_31.material} position={[8.986, 7.506, -4.357]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_43.geometry} material={nodes.GN_Instance_43.material} position={[-3.364, 7.511, 3.481]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_44.geometry} material={nodes.GN_Instance_44.material} position={[-3.364, 7.511, 5.253]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_45.geometry} material={nodes.GN_Instance_45.material} position={[-3.364, 7.511, 7.043]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_46.geometry} material={nodes.GN_Instance_46.material} position={[-3.364, 3.312, 7.043]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_47.geometry} material={nodes.GN_Instance_47.material} position={[-3.364, 3.312, 5.253]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_48.geometry} material={nodes.GN_Instance_48.material} position={[-3.364, 3.312, 3.483]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_49.geometry} material={nodes.GN_Instance_49.material} position={[-4.405, 7.511, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_50.geometry} material={nodes.GN_Instance_50.material} position={[-6.288, 7.511, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_51.geometry} material={nodes.GN_Instance_51.material} position={[-6.279, 3.312, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_52.geometry} material={nodes.GN_Instance_52.material} position={[-4.404, 3.312, 1.881]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_61.geometry} material={nodes.GN_Instance_61.material} position={[-6.283, 7.511, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_62.geometry} material={nodes.GN_Instance_62.material} position={[-4.396, 7.511, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_63.geometry} material={nodes.GN_Instance_63.material} position={[-6.283, 3.342, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_64.geometry} material={nodes.GN_Instance_64.material} position={[-4.427, 3.342, 8.839]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_70.geometry} material={nodes.GN_Instance_70.material} position={[-7.34, 7.511, 3.481]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_71.geometry} material={nodes.GN_Instance_71.material} position={[-7.34, 7.511, 5.253]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_72.geometry} material={nodes.GN_Instance_72.material} position={[-7.34, 7.511, 7.043]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_73.geometry} material={nodes.GN_Instance_73.material} position={[-7.376, 3.312, 3.483]} rotation={[0, -1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_74.geometry} material={nodes.GN_Instance_74.material} position={[-7.928, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_75.geometry} material={nodes.GN_Instance_75.material} position={[-6.144, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_76.geometry} material={nodes.GN_Instance_76.material} position={[-4.375, 7.506, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_77.geometry} material={nodes.GN_Instance_77.material} position={[-4.375, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_78.geometry} material={nodes.GN_Instance_78.material} position={[-6.139, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_79.geometry} material={nodes.GN_Instance_79.material} position={[-7.929, 3.311, -2.65]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_80.geometry} material={nodes.GN_Instance_80.material} position={[-2.766, 3.311, -3.698]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_81.geometry} material={nodes.GN_Instance_81.material} position={[-2.766, 3.311, -5.571]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_82.geometry} material={nodes.GN_Instance_82.material} position={[-2.766, 7.503, -5.571]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_83.geometry} material={nodes.GN_Instance_83.material} position={[-2.766, 7.503, -3.699]} rotation={[0, 1.571, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_92.geometry} material={nodes.GN_Instance_92.material} position={[-5.947, 4.665, 20.7]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_15.geometry} material={nodes.GN_Instance_15.material} position={[7.204, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_16.geometry} material={nodes.GN_Instance_16.material} position={[5.418, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_17.geometry} material={nodes.GN_Instance_17.material} position={[3.636, 5.39, -5.349]} rotation={[-Math.PI, 0, Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_18.geometry} material={nodes.GN_Instance_18.material} position={[2.09, 5.39, -4.368]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_19.geometry} material={nodes.GN_Instance_19.material} position={[2.09, 5.39, -2.493]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_20.geometry} material={nodes.GN_Instance_20.material} position={[3.635, 5.39, -1.509]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_23.geometry} material={nodes.GN_Instance_23.material} position={[5.422, 5.39, -1.509]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_24.geometry} material={nodes.GN_Instance_24.material} position={[7.202, 5.39, -1.509]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_29.geometry} material={nodes.GN_Instance_29.material} position={[8.929, 5.39, -2.493]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_32.geometry} material={nodes.GN_Instance_32.material} position={[8.929, 5.39, -4.361]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_53.geometry} material={nodes.GN_Instance_53.material} position={[-3.424, 5.393, 7.044]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_54.geometry} material={nodes.GN_Instance_54.material} position={[-3.424, 5.393, 5.264]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_55.geometry} material={nodes.GN_Instance_55.material} position={[-3.424, 5.393, 3.476]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_56.geometry} material={nodes.GN_Instance_56.material} position={[-4.408, 5.382, 1.922]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_57.geometry} material={nodes.GN_Instance_57.material} position={[-6.279, 5.382, 1.922]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_65.geometry} material={nodes.GN_Instance_65.material} position={[-6.298, 5.393, 8.757]} rotation={[0, 0.017, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_66.geometry} material={nodes.GN_Instance_66.material} position={[-4.418, 5.393, 8.757]} rotation={[0, 0.017, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_67.geometry} material={nodes.GN_Instance_67.material} position={[-7.278, 5.393, 7.044]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_68.geometry} material={nodes.GN_Instance_68.material} position={[-7.278, 5.393, 5.264]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_69.geometry} material={nodes.GN_Instance_69.material} position={[-7.278, 5.393, 3.476]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_84.geometry} material={nodes.GN_Instance_84.material} position={[-7.858, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_85.geometry} material={nodes.GN_Instance_85.material} position={[-6.154, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_86.geometry} material={nodes.GN_Instance_86.material} position={[-4.376, 5.393, -2.712]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_87.geometry} material={nodes.GN_Instance_87.material} position={[-2.821, 5.393, -3.681]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_88.geometry} material={nodes.GN_Instance_88.material} position={[-2.821, 5.393, -5.561]} rotation={[0, Math.PI / 2, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony.geometry} material={nodes.Balcony.material} position={[2.281, 4.184, 2.723]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_33.geometry} material={nodes.GN_Instance_33.material} position={[2.281, 4.184, 2.723]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_1.geometry} material={nodes.Balcony_1.material} position={[2.281, 4.184, 4.754]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_35.geometry} material={nodes.GN_Instance_35.material} position={[2.281, 4.184, 4.754]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_Column004.geometry} material={nodes.Balcony_Column004.material} position={[2.043, 4.272, 2.583]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_34.geometry} material={nodes.GN_Instance_34.material} position={[2.043, 4.272, 2.583]} />
      <mesh castShadow receiveShadow geometry={nodes.Balcony_Column004_1.geometry} material={nodes.Balcony_Column004_1.material} position={[2.043, 4.272, 4.614]} />
      <mesh castShadow receiveShadow geometry={nodes.GN_Instance_36.geometry} material={nodes.GN_Instance_36.material} position={[2.043, 4.272, 4.614]} />
      <instancedMesh args={[nodes.SpeakerSpawner.geometry, nodes.SpeakerSpawner.material, 12]} castShadow receiveShadow instanceMatrix={nodes.SpeakerSpawner.instanceMatrix} position={[3.118, 0.734, 18.787]} rotation={[0, -0.42, 0]} />
      <instancedMesh args={[nodes.Window0210.geometry, nodes.Window0210.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0210.instanceMatrix} position={[3.737, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0220.geometry, nodes.Window0220.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0220.instanceMatrix} position={[3.737, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0230.geometry, nodes.Window0230.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0230.instanceMatrix} position={[2.024, 3.317, -2.508]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0240.geometry, nodes.Window0240.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0240.instanceMatrix} position={[2.024, 3.317, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0250.geometry, nodes.Window0250.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0250.instanceMatrix} position={[3.637, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0260.geometry, nodes.Window0260.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0260.instanceMatrix} position={[2.024, 7.506, -2.495]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0270.geometry, nodes.Window0270.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0270.instanceMatrix} position={[2.024, 7.506, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0280.geometry, nodes.Window0280.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0280.instanceMatrix} position={[3.637, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0290.geometry, nodes.Window0290.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0290.instanceMatrix} position={[5.418, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0300.geometry, nodes.Window0300.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0300.instanceMatrix} position={[7.186, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0310.geometry, nodes.Window0310.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0310.instanceMatrix} position={[5.423, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0320.geometry, nodes.Window0320.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0320.instanceMatrix} position={[7.228, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60060.geometry, nodes.Window60060.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60060.instanceMatrix} position={[7.204, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60070.geometry, nodes.Window60070.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60070.instanceMatrix} position={[5.418, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60080.geometry, nodes.Window60080.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60080.instanceMatrix} position={[3.636, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60090.geometry, nodes.Window60090.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60090.instanceMatrix} position={[2.09, 5.39, -4.368]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60100.geometry, nodes.Window60100.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60100.instanceMatrix} position={[2.09, 5.39, -2.493]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60110.geometry, nodes.Window60110.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60110.instanceMatrix} position={[3.635, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0410.geometry, nodes.Window0410.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0410.instanceMatrix} position={[5.444, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0420.geometry, nodes.Window0420.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0420.instanceMatrix} position={[7.198, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60220.geometry, nodes.Window60220.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60220.instanceMatrix} position={[5.422, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60230.geometry, nodes.Window60230.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60230.instanceMatrix} position={[7.202, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0430.geometry, nodes.Window0430.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0430.instanceMatrix} position={[5.432, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0440.geometry, nodes.Window0440.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0440.instanceMatrix} position={[7.206, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0450.geometry, nodes.Window0450.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0450.instanceMatrix} position={[8.982, 3.317, -2.508]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0460.geometry, nodes.Window0460.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0460.instanceMatrix} position={[8.982, 3.317, -4.379]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60240.geometry, nodes.Window60240.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60240.instanceMatrix} position={[8.929, 5.39, -2.493]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0470.geometry, nodes.Window0470.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0470.instanceMatrix} position={[8.986, 7.506, -2.495]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0480.geometry, nodes.Window0480.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0480.instanceMatrix} position={[8.986, 7.506, -4.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60250.geometry, nodes.Window60250.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60250.instanceMatrix} position={[8.929, 5.39, -4.361]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0010.geometry, nodes.Window0010.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0010.instanceMatrix} position={[-3.364, 7.511, 3.481]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0020.geometry, nodes.Window0020.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0020.instanceMatrix} position={[-3.364, 7.511, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0030.geometry, nodes.Window0030.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0030.instanceMatrix} position={[-3.364, 7.511, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0040.geometry, nodes.Window0040.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0040.instanceMatrix} position={[-3.364, 3.312, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0050.geometry, nodes.Window0050.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0050.instanceMatrix} position={[-3.364, 3.312, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0060.geometry, nodes.Window0060.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0060.instanceMatrix} position={[-3.364, 3.312, 3.483]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0070.geometry, nodes.Window0070.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0070.instanceMatrix} position={[-4.405, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0080.geometry, nodes.Window0080.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0080.instanceMatrix} position={[-6.288, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0090.geometry, nodes.Window0090.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0090.instanceMatrix} position={[-6.279, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0100.geometry, nodes.Window0100.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0100.instanceMatrix} position={[-4.404, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60010.geometry, nodes.Window60010.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60010.instanceMatrix} position={[-3.424, 5.393, 7.044]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60020.geometry, nodes.Window60020.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60020.instanceMatrix} position={[-3.424, 5.393, 5.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60030.geometry, nodes.Window60030.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60030.instanceMatrix} position={[-3.424, 5.393, 3.476]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60040.geometry, nodes.Window60040.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60040.instanceMatrix} position={[-4.408, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60050.geometry, nodes.Window60050.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60050.instanceMatrix} position={[-6.279, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0330.geometry, nodes.Window0330.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0330.instanceMatrix} position={[-6.283, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0340.geometry, nodes.Window0340.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0340.instanceMatrix} position={[-4.396, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0350.geometry, nodes.Window0350.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0350.instanceMatrix} position={[-6.283, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0360.geometry, nodes.Window0360.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0360.instanceMatrix} position={[-4.427, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60170.geometry, nodes.Window60170.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60170.instanceMatrix} position={[-6.298, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60180.geometry, nodes.Window60180.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60180.instanceMatrix} position={[-4.418, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60190.geometry, nodes.Window60190.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60190.instanceMatrix} position={[-7.278, 5.393, 7.044]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60200.geometry, nodes.Window60200.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60200.instanceMatrix} position={[-7.278, 5.393, 5.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60210.geometry, nodes.Window60210.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60210.instanceMatrix} position={[-7.278, 5.393, 3.476]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0370.geometry, nodes.Window0370.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0370.instanceMatrix} position={[-7.34, 7.511, 3.481]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0380.geometry, nodes.Window0380.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0380.instanceMatrix} position={[-7.34, 7.511, 5.253]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0390.geometry, nodes.Window0390.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0390.instanceMatrix} position={[-7.34, 7.511, 7.043]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0400.geometry, nodes.Window0400.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0400.instanceMatrix} position={[-7.376, 3.312, 3.483]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0110.geometry, nodes.Window0110.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0110.instanceMatrix} position={[-7.928, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0120.geometry, nodes.Window0120.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0120.instanceMatrix} position={[-6.144, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0130.geometry, nodes.Window0130.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0130.instanceMatrix} position={[-4.375, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0140.geometry, nodes.Window0140.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0140.instanceMatrix} position={[-4.375, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0150.geometry, nodes.Window0150.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0150.instanceMatrix} position={[-6.139, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0160.geometry, nodes.Window0160.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0160.instanceMatrix} position={[-7.929, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0170.geometry, nodes.Window0170.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0170.instanceMatrix} position={[-2.766, 3.311, -3.698]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0180.geometry, nodes.Window0180.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0180.instanceMatrix} position={[-2.766, 3.311, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0190.geometry, nodes.Window0190.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0190.instanceMatrix} position={[-2.766, 7.503, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0200.geometry, nodes.Window0200.material, 8]} castShadow receiveShadow instanceMatrix={nodes.Window0200.instanceMatrix} position={[-2.766, 7.503, -3.699]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60120.geometry, nodes.Window60120.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60120.instanceMatrix} position={[-7.858, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60130.geometry, nodes.Window60130.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60130.instanceMatrix} position={[-6.154, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60140.geometry, nodes.Window60140.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60140.instanceMatrix} position={[-4.376, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60150.geometry, nodes.Window60150.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60150.instanceMatrix} position={[-2.821, 5.393, -3.681]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60160.geometry, nodes.Window60160.material, 12]} castShadow receiveShadow instanceMatrix={nodes.Window60160.instanceMatrix} position={[-2.821, 5.393, -5.561]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.WindowShutter40010.geometry, nodes.WindowShutter40010.material, 8]} castShadow receiveShadow instanceMatrix={nodes.WindowShutter40010.instanceMatrix} position={[-5.947, 4.665, 20.7]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0211.geometry, nodes.Window0211.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0211.instanceMatrix} position={[3.737, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0221.geometry, nodes.Window0221.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0221.instanceMatrix} position={[3.737, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0231.geometry, nodes.Window0231.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0231.instanceMatrix} position={[2.024, 3.317, -2.508]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0241.geometry, nodes.Window0241.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0241.instanceMatrix} position={[2.024, 3.317, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0251.geometry, nodes.Window0251.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0251.instanceMatrix} position={[3.637, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0261.geometry, nodes.Window0261.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0261.instanceMatrix} position={[2.024, 7.506, -2.495]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0271.geometry, nodes.Window0271.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0271.instanceMatrix} position={[2.024, 7.506, -4.371]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0281.geometry, nodes.Window0281.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0281.instanceMatrix} position={[3.637, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0291.geometry, nodes.Window0291.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0291.instanceMatrix} position={[5.418, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0301.geometry, nodes.Window0301.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0301.instanceMatrix} position={[7.186, 7.506, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0311.geometry, nodes.Window0311.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0311.instanceMatrix} position={[5.423, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0321.geometry, nodes.Window0321.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0321.instanceMatrix} position={[7.228, 3.324, -5.425]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window0411.geometry, nodes.Window0411.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0411.instanceMatrix} position={[5.444, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0421.geometry, nodes.Window0421.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0421.instanceMatrix} position={[7.198, 7.497, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0431.geometry, nodes.Window0431.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0431.instanceMatrix} position={[5.432, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0441.geometry, nodes.Window0441.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0441.instanceMatrix} position={[7.206, 3.317, -1.446]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0451.geometry, nodes.Window0451.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0451.instanceMatrix} position={[8.982, 3.317, -2.508]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0461.geometry, nodes.Window0461.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0461.instanceMatrix} position={[8.982, 3.317, -4.379]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0471.geometry, nodes.Window0471.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0471.instanceMatrix} position={[8.986, 7.506, -2.495]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0481.geometry, nodes.Window0481.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0481.instanceMatrix} position={[8.986, 7.506, -4.357]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0011.geometry, nodes.Window0011.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0011.instanceMatrix} position={[-3.364, 7.511, 3.481]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0021.geometry, nodes.Window0021.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0021.instanceMatrix} position={[-3.364, 7.511, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0031.geometry, nodes.Window0031.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0031.instanceMatrix} position={[-3.364, 7.511, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0041.geometry, nodes.Window0041.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0041.instanceMatrix} position={[-3.364, 3.312, 7.043]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0051.geometry, nodes.Window0051.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0051.instanceMatrix} position={[-3.364, 3.312, 5.253]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0061.geometry, nodes.Window0061.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0061.instanceMatrix} position={[-3.364, 3.312, 3.483]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0071.geometry, nodes.Window0071.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0071.instanceMatrix} position={[-4.405, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0081.geometry, nodes.Window0081.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0081.instanceMatrix} position={[-6.288, 7.511, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0091.geometry, nodes.Window0091.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0091.instanceMatrix} position={[-6.279, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0101.geometry, nodes.Window0101.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0101.instanceMatrix} position={[-4.404, 3.312, 1.881]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window0331.geometry, nodes.Window0331.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0331.instanceMatrix} position={[-6.283, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0341.geometry, nodes.Window0341.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0341.instanceMatrix} position={[-4.396, 7.511, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0351.geometry, nodes.Window0351.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0351.instanceMatrix} position={[-6.283, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0361.geometry, nodes.Window0361.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0361.instanceMatrix} position={[-4.427, 3.342, 8.839]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0371.geometry, nodes.Window0371.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0371.instanceMatrix} position={[-7.34, 7.511, 3.481]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0381.geometry, nodes.Window0381.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0381.instanceMatrix} position={[-7.34, 7.511, 5.253]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0391.geometry, nodes.Window0391.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0391.instanceMatrix} position={[-7.34, 7.511, 7.043]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0401.geometry, nodes.Window0401.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0401.instanceMatrix} position={[-7.376, 3.312, 3.483]} rotation={[Math.PI / 2, 0, 1.571]} />
      <instancedMesh args={[nodes.Window0111.geometry, nodes.Window0111.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0111.instanceMatrix} position={[-7.928, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0121.geometry, nodes.Window0121.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0121.instanceMatrix} position={[-6.144, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0131.geometry, nodes.Window0131.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0131.instanceMatrix} position={[-4.375, 7.506, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0141.geometry, nodes.Window0141.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0141.instanceMatrix} position={[-4.375, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0151.geometry, nodes.Window0151.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0151.instanceMatrix} position={[-6.139, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0161.geometry, nodes.Window0161.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0161.instanceMatrix} position={[-7.929, 3.311, -2.65]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window0171.geometry, nodes.Window0171.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0171.instanceMatrix} position={[-2.766, 3.311, -3.698]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0181.geometry, nodes.Window0181.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0181.instanceMatrix} position={[-2.766, 3.311, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0191.geometry, nodes.Window0191.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0191.instanceMatrix} position={[-2.766, 7.503, -5.571]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window0201.geometry, nodes.Window0201.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window0201.instanceMatrix} position={[-2.766, 7.503, -3.699]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.WindowShutter40011.geometry, nodes.WindowShutter40011.material, 2]} castShadow receiveShadow instanceMatrix={nodes.WindowShutter40011.instanceMatrix} position={[-5.947, 4.665, 20.7]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60061.geometry, nodes.Window60061.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60061.instanceMatrix} position={[7.204, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60071.geometry, nodes.Window60071.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60071.instanceMatrix} position={[5.418, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60081.geometry, nodes.Window60081.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60081.instanceMatrix} position={[3.636, 5.39, -5.349]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <instancedMesh args={[nodes.Window60091.geometry, nodes.Window60091.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60091.instanceMatrix} position={[2.09, 5.39, -4.368]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60101.geometry, nodes.Window60101.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60101.instanceMatrix} position={[2.09, 5.39, -2.493]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60111.geometry, nodes.Window60111.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60111.instanceMatrix} position={[3.635, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60221.geometry, nodes.Window60221.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60221.instanceMatrix} position={[5.422, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60231.geometry, nodes.Window60231.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60231.instanceMatrix} position={[7.202, 5.39, -1.509]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60241.geometry, nodes.Window60241.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60241.instanceMatrix} position={[8.929, 5.39, -2.493]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60251.geometry, nodes.Window60251.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60251.instanceMatrix} position={[8.929, 5.39, -4.361]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60011.geometry, nodes.Window60011.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60011.instanceMatrix} position={[-3.424, 5.393, 7.044]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60021.geometry, nodes.Window60021.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60021.instanceMatrix} position={[-3.424, 5.393, 5.264]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60031.geometry, nodes.Window60031.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60031.instanceMatrix} position={[-3.424, 5.393, 3.476]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60041.geometry, nodes.Window60041.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60041.instanceMatrix} position={[-4.408, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60051.geometry, nodes.Window60051.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60051.instanceMatrix} position={[-6.279, 5.382, 1.922]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <instancedMesh args={[nodes.Window60171.geometry, nodes.Window60171.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60171.instanceMatrix} position={[-6.298, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60181.geometry, nodes.Window60181.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60181.instanceMatrix} position={[-4.418, 5.393, 8.757]} rotation={[Math.PI / 2, 0, -0.017]} />
      <instancedMesh args={[nodes.Window60191.geometry, nodes.Window60191.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60191.instanceMatrix} position={[-7.278, 5.393, 7.044]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60201.geometry, nodes.Window60201.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60201.instanceMatrix} position={[-7.278, 5.393, 5.264]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60211.geometry, nodes.Window60211.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60211.instanceMatrix} position={[-7.278, 5.393, 3.476]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60121.geometry, nodes.Window60121.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60121.instanceMatrix} position={[-7.858, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60131.geometry, nodes.Window60131.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60131.instanceMatrix} position={[-6.154, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60141.geometry, nodes.Window60141.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60141.instanceMatrix} position={[-4.376, 5.393, -2.712]} rotation={[Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.Window60151.geometry, nodes.Window60151.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60151.instanceMatrix} position={[-2.821, 5.393, -3.681]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Window60161.geometry, nodes.Window60161.material, 2]} castShadow receiveShadow instanceMatrix={nodes.Window60161.instanceMatrix} position={[-2.821, 5.393, -5.561]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <instancedMesh args={[nodes.Balcony0010.geometry, nodes.Balcony0010.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony0010.instanceMatrix} position={[2.281, 4.184, 2.723]} rotation={[0, -Math.PI / 2, 0]} />
      <instancedMesh args={[nodes.Balcony0011.geometry, nodes.Balcony0011.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony0011.instanceMatrix} position={[2.281, 4.184, 2.723]} rotation={[0, -Math.PI / 2, 0]} />
      <instancedMesh args={[nodes.Balcony0020.geometry, nodes.Balcony0020.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony0020.instanceMatrix} position={[2.281, 4.184, 4.754]} rotation={[0, -Math.PI / 2, 0]} />
      <instancedMesh args={[nodes.Balcony0021.geometry, nodes.Balcony0021.material, 6]} castShadow receiveShadow instanceMatrix={nodes.Balcony0021.instanceMatrix} position={[2.281, 4.184, 4.754]} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/assets/venice-transformed.glb')

