/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/gondola.glb -T -s -k --root=./public --output=public/assets/gondola.jsx 
Files: public/assets/gondola.glb [43.18KB] > D:\projects\venezia-website\public\assets\gondola-transformed.glb [7.43KB] (83%)
*/

import React from 'react'
import { useGLTF, useAnimations, PerspectiveCamera } from '@react-three/drei'
import { Player } from '../player'

export function Model ( props ) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF( '/assets/gondola-transformed.glb' )
  const { actions } = useAnimations( animations, group )
  return (
    <group ref={ group } { ...props } dispose={ null }>
      <group name="Scene">
        <mesh onClick={ () => actions[ "GondolaAction" ].play() } name="Gondola" castShadow receiveShadow geometry={ nodes.Gondola.geometry } material={ nodes.Gondola.material } position={ [ -14.523, 0, 10.434 ] } rotation={ [ 0, 0, 1.658 ] }>
          <mesh name="Gondola_Rudder" castShadow receiveShadow geometry={ nodes.Gondola_Rudder.geometry } material={ nodes.Gondola_Rudder.material } position={ [ 0.493, 1.691, 0.303 ] } />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload( '/assets/gondola-transformed.glb' )
