import styles from "./styles.module.css";

export const metadata = {
  title: 'Index of /~venice/projects/',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="color-scheme" content="dark light"></meta>
      <body className={styles.body} >{children}</body>
    </html>
  )
}
